function plotVerticalFrequencyResponse(FrequencyResponse)
%PLOTVERTICALFREQUENCYRESPONSE
%
% Stage 5.7B - Quarter-Car Frequency Response


f = FrequencyResponse.frequency;


%% ============================================================
% FIGURE 1 - BODY RESPONSE
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7B - Figure 1 - Body Frequency Response');

semilogx( ...
    f, ...
    FrequencyResponse.bodyTransmissibility, ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Z_s / Z_r| [-]');

title( ...
    'Stage 5.7B - Figure 1 - Sprung-Mass Frequency Response');

xline( ...
    FrequencyResponse.bodyNaturalFrequency, ...
    '--', ...
    'Undamped Body Mode');

xline( ...
    FrequencyResponse.wheelHopNaturalFrequency, ...
    '--', ...
    'Undamped Wheel-Hop Mode');


%% ============================================================
% FIGURE 2 - WHEEL RESPONSE
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7B - Figure 2 - Wheel Frequency Response');

semilogx( ...
    f, ...
    FrequencyResponse.wheelTransmissibility, ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Z_u / Z_r| [-]');

title( ...
    'Stage 5.7B - Figure 2 - Unsprung-Mass Frequency Response');

xline( ...
    FrequencyResponse.bodyNaturalFrequency, ...
    '--', ...
    'Undamped Body Mode');

xline( ...
    FrequencyResponse.wheelHopNaturalFrequency, ...
    '--', ...
    'Undamped Wheel-Hop Mode');


%% ============================================================
% FIGURE 3 - SUSPENSION TRAVEL
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7B - Figure 3 - Suspension Travel Response');

semilogx( ...
    f, ...
    FrequencyResponse.suspensionTravelRatio, ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Z_s - Z_u| / |Z_r| [-]');

title( ...
    'Stage 5.7B - Figure 3 - Suspension Travel Frequency Response');

xline( ...
    FrequencyResponse.bodyNaturalFrequency, ...
    '--', ...
    'Body Mode');

xline( ...
    FrequencyResponse.wheelHopNaturalFrequency, ...
    '--', ...
    'Wheel-Hop Mode');


%% ============================================================
% FIGURE 4 - DYNAMIC TYRE LOAD
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7B - Figure 4 - Dynamic Tyre Load Response');

semilogx( ...
    f, ...
    FrequencyResponse.tyreLoadSensitivity / 1000, ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Delta F_z| / |Z_r| [kN/m]');

title( ...
    'Stage 5.7B - Figure 4 - Dynamic Tyre Load Sensitivity');

xline( ...
    FrequencyResponse.bodyNaturalFrequency, ...
    '--', ...
    'Body Mode');

xline( ...
    FrequencyResponse.wheelHopNaturalFrequency, ...
    '--', ...
    'Wheel-Hop Mode');


end