function plotAeroSuspensionEquilibrium(Equilibrium)
%PLOTAEROSUSPENSIONEQUILIBRIUM
%
% Stage 5.5 - Aero-Suspension Solver Convergence


iterations = 1:Equilibrium.iterations;


%% ============================================================
% FIGURE 1 - RIDE HEIGHT CONVERGENCE
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.5 - Figure 1 - Ride Height Convergence');

plot( ...
    iterations, ...
    Equilibrium.frontRHHistory, ...
    '-o', ...
    'LineWidth',1.5);

hold on;

plot( ...
    iterations, ...
    Equilibrium.rearRHHistory, ...
    '-s', ...
    'LineWidth',1.5);

grid on;

xlabel('Iteration');
ylabel('Ride Height [mm]');

title( ...
    'Stage 5.5 - Figure 1 - Ride Height Convergence');

legend( ...
    'Front Ride Height', ...
    'Rear Ride Height', ...
    'Location','best');


%% ============================================================
% FIGURE 2 - AERODYNAMIC CONVERGENCE
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.5 - Figure 2 - Aerodynamic Convergence');

plot( ...
    iterations, ...
    Equilibrium.downforceHistory, ...
    '-o', ...
    'LineWidth',1.5);

grid on;

xlabel('Iteration');
ylabel('Downforce [N]');

title( ...
    'Stage 5.5 - Figure 2 - Aerodynamic Load Convergence');


%% ============================================================
% FIGURE 3 - EQUILIBRIUM ERROR
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.5 - Figure 3 - Equilibrium Error');

semilogy( ...
    iterations, ...
    Equilibrium.errorHistory, ...
    '-o', ...
    'LineWidth',1.5);

grid on;

xlabel('Iteration');
ylabel('Maximum Ride Height Error [mm]');

title( ...
    'Stage 5.5 - Figure 3 - Equilibrium Solver Error');


end