function plotVerticalTimeDomainStudy(Study)
%PLOTVERTICALTIMEDOMAINSTUDY
%
% Stage 5.7D - Time-Domain Road Excitation


B = Study.Baseline;
S = Study.Stiffer;

t = B.time;


%% ============================================================
% FIGURE 1 - ROAD INPUT
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7D - Figure 1 - Road Excitation');

plot( ...
    t, ...
    B.road * 1000, ...
    'LineWidth',1.6);

grid on;

xlabel('Time [s]');
ylabel('Road Displacement [mm]');

title( ...
    'Stage 5.7D - Figure 1 - Road Excitation');


%% ============================================================
% FIGURE 2 - SPRUNG-MASS DISPLACEMENT
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7D - Figure 2 - Body Displacement');

plot( ...
    t, ...
    B.zs * 1000, ...
    'LineWidth',1.6);

hold on;

plot( ...
    t, ...
    S.zs * 1000, ...
    '--', ...
    'LineWidth',1.6);

grid on;

xlabel('Time [s]');
ylabel('Sprung-Mass Displacement [mm]');

title( ...
    'Stage 5.7D - Figure 2 - Sprung-Mass Response');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 3 - SUSPENSION TRAVEL
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7D - Figure 3 - Suspension Travel');

plot( ...
    t, ...
    B.suspensionTravel * 1000, ...
    'LineWidth',1.6);

hold on;

plot( ...
    t, ...
    S.suspensionTravel * 1000, ...
    '--', ...
    'LineWidth',1.6);

grid on;

xlabel('Time [s]');
ylabel('Suspension Travel [mm]');

title( ...
    'Stage 5.7D - Figure 3 - Suspension Travel Response');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 4 - BODY ACCELERATION
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7D - Figure 4 - Body Acceleration');

plot( ...
    t, ...
    B.zsAcceleration, ...
    'LineWidth',1.6);

hold on;

plot( ...
    t, ...
    S.zsAcceleration, ...
    '--', ...
    'LineWidth',1.6);

grid on;

xlabel('Time [s]');
ylabel('Sprung-Mass Acceleration [m/s^2]');

title( ...
    'Stage 5.7D - Figure 4 - Sprung-Mass Acceleration');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 5 - DYNAMIC TYRE LOAD
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7D - Figure 5 - Dynamic Tyre Load');

plot( ...
    t, ...
    B.dynamicTyreLoad, ...
    'LineWidth',1.6);

hold on;

plot( ...
    t, ...
    S.dynamicTyreLoad, ...
    '--', ...
    'LineWidth',1.6);

yline(0,'k:');

grid on;

xlabel('Time [s]');
ylabel('\Delta F_z [N]');

title( ...
    'Stage 5.7D - Figure 5 - Dynamic Tyre Load Variation');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


end