function plotVerticalFFTStudy(Study)
%PLOTVERTICALFFTSTUDY
%
% Stage 5.7E - FFT / Spectral Analysis


B = Study.BaselineFFT;
S = Study.StifferFFT;


%% ============================================================
% FIGURE 1 - BODY ACCELERATION FFT
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7E - Figure 1 - Body Acceleration FFT');

plot( ...
    B.frequency, ...
    B.bodySpectrum, ...
    'LineWidth',1.6);

hold on;

plot( ...
    S.frequency, ...
    S.bodySpectrum, ...
    '--', ...
    'LineWidth',1.6);


xline( ...
    Study.baselineBodyMode, ...
    ':', ...
    'Baseline Body Mode', ...
    'LabelVerticalAlignment','middle');

xline( ...
    Study.stifferBodyMode, ...
    ':', ...
    '1.15x Body Mode', ...
    'LabelVerticalAlignment','bottom');


grid on;

xlim([0 30]);

xlabel('Frequency [Hz]');
ylabel('Normalised FFT Magnitude [-]');

title( ...
    'Stage 5.7E - Figure 1 - Sprung-Mass Acceleration Spectrum');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 2 - DYNAMIC TYRE LOAD FFT
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7E - Figure 2 - Dynamic Tyre Load FFT');

plot( ...
    B.frequency, ...
    B.tyreSpectrum, ...
    'LineWidth',1.6);

hold on;

plot( ...
    S.frequency, ...
    S.tyreSpectrum, ...
    '--', ...
    'LineWidth',1.6);


xline( ...
    Study.baselineBodyMode, ...
    ':', ...
    'Body Mode', ...
    'LabelVerticalAlignment','middle');

xline( ...
    Study.baselineWheelHop, ...
    ':', ...
    'Wheel-Hop Mode', ...
    'LabelVerticalAlignment','middle');


grid on;

xlim([0 30]);

xlabel('Frequency [Hz]');
ylabel('Normalised FFT Magnitude [-]');

title( ...
    'Stage 5.7E - Figure 2 - Dynamic Tyre Load Spectrum');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 3 - BODY-MODE DETAIL
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7E - Figure 3 - Body Mode Detail');

plot( ...
    B.frequency, ...
    B.bodySpectrum, ...
    'LineWidth',1.6);

hold on;

plot( ...
    S.frequency, ...
    S.bodySpectrum, ...
    '--', ...
    'LineWidth',1.6);


xline( ...
    Study.baselineBodyMode, ...
    ':', ...
    sprintf('Predicted 1.00x = %.2f Hz', ...
    Study.baselineBodyMode));

xline( ...
    Study.stifferBodyMode, ...
    ':', ...
    sprintf('Predicted 1.15x = %.2f Hz', ...
    Study.stifferBodyMode));


grid on;

xlim([1 8]);

xlabel('Frequency [Hz]');
ylabel('Normalised FFT Magnitude [-]');

title( ...
    'Stage 5.7E - Figure 3 - Body Mode Spectral Detail');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


end