function plotVerticalSetupTradeoff(Study)
%PLOTVERTICALSETUPTRADEOFF
%
% Stage 5.7C - Vertical Dynamics Setup Trade-Off


f = Study.FrequencyBaseline.frequency;

B = Study.FrequencyBaseline;
S = Study.FrequencyStiffer;


%% ============================================================
% FIGURE 1 - BODY RESPONSE
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7C - Figure 1 - Setup vs Body Response');

semilogx( ...
    f, ...
    B.bodyTransmissibility, ...
    'LineWidth',1.6);

hold on;

semilogx( ...
    f, ...
    S.bodyTransmissibility, ...
    '--', ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Z_s / Z_r| [-]');

title( ...
    'Stage 5.7C - Figure 1 - Spring Setup vs Body Response');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 2 - SUSPENSION TRAVEL
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7C - Figure 2 - Setup vs Suspension Travel');

semilogx( ...
    f, ...
    B.suspensionTravelRatio, ...
    'LineWidth',1.6);

hold on;

semilogx( ...
    f, ...
    S.suspensionTravelRatio, ...
    '--', ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Z_s - Z_u| / |Z_r| [-]');

title( ...
    'Stage 5.7C - Figure 2 - Spring Setup vs Suspension Travel');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 3 - DYNAMIC TYRE LOAD
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7C - Figure 3 - Setup vs Dynamic Tyre Load');

semilogx( ...
    f, ...
    B.tyreLoadSensitivity / 1000, ...
    'LineWidth',1.6);

hold on;

semilogx( ...
    f, ...
    S.tyreLoadSensitivity / 1000, ...
    '--', ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Delta F_z| / |Z_r| [kN/m]');

title( ...
    'Stage 5.7C - Figure 3 - Spring Setup vs Dynamic Tyre Load');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


%% ============================================================
% FIGURE 4 - UNSPRUNG MASS RESPONSE
% ============================================================

figure( ...
    'Name', ...
    'Stage 5.7C - Figure 4 - Setup vs Wheel Response');

semilogx( ...
    f, ...
    B.wheelTransmissibility, ...
    'LineWidth',1.6);

hold on;

semilogx( ...
    f, ...
    S.wheelTransmissibility, ...
    '--', ...
    'LineWidth',1.6);

grid on;

xlabel('Frequency [Hz]');
ylabel('|Z_u / Z_r| [-]');

title( ...
    'Stage 5.7C - Figure 4 - Spring Setup vs Wheel Response');

legend( ...
    'Baseline - 1.00x', ...
    'Platform Controlled - 1.15x', ...
    'Location','best');


end