function plotSpringTradeoffMap(Study)
%PLOTSPRINGTRADEOFFMAP
%
% Stage 6.4 - Front / Rear Spring Trade-Off Visualisation


F = ...
    Study.FrontSpringGrid;

Rr = ...
    Study.RearSpringGrid;

Data = ...
    Study.Results;


baselineFront = ...
    Study.baselineFrontSpring;

baselineRear = ...
    Study.baselineRearSpring;


%% ============================================================
% FIGURE 1 - DOWNFORCE MAP
% ============================================================

figure( ...
    'Name', ...
    'Stage 6.4 - Figure 1 - Spring Trade-Off - Downforce');


contourf( ...
    F, ...
    Rr, ...
    Data.downforce, ...
    20);

hold on;

colorbar;


% Aero-map validity boundary
contour( ...
    F, ...
    Rr, ...
    Data.minimumAeroMargin, ...
    [0 0], ...
    'k', ...
    'LineWidth',2.0);


% Baseline setup
plot( ...
    baselineFront, ...
    baselineRear, ...
    'kx', ...
    'MarkerSize',12, ...
    'LineWidth',2.0);


% Maximum valid downforce point
if ~isnan(Study.maximumValidDownforce)

    plot( ...
        Study.maxDownforceFrontSpring, ...
        Study.maxDownforceRearSpring, ...
        'ko', ...
        'MarkerSize',8, ...
        'LineWidth',2.0);

end


grid on;

xlabel('Front Spring Rate [N/mm]');
ylabel('Rear Spring Rate [N/mm]');

title( ...
    'Stage 6.4 - Figure 1 - Downforce Trade-Off Map');


%% ============================================================
% FIGURE 2 - MINIMUM AERO-MAP MARGIN
% ============================================================

figure( ...
    'Name', ...
    'Stage 6.4 - Figure 2 - Spring Trade-Off - Aero Map Margin');


contourf( ...
    F, ...
    Rr, ...
    Data.minimumAeroMargin, ...
    20);

hold on;

colorbar;


contour( ...
    F, ...
    Rr, ...
    Data.minimumAeroMargin, ...
    [0 0], ...
    'k', ...
    'LineWidth',2.5);


plot( ...
    baselineFront, ...
    baselineRear, ...
    'kx', ...
    'MarkerSize',12, ...
    'LineWidth',2.0);


grid on;

xlabel('Front Spring Rate [N/mm]');
ylabel('Rear Spring Rate [N/mm]');

title( ...
    'Stage 6.4 - Figure 2 - Aero-Map Margin');


%% ============================================================
% FIGURE 3 - VEHICLE BALANCE
% ============================================================

figure( ...
    'Name', ...
    'Stage 6.4 - Figure 3 - Spring Trade-Off - Vehicle Balance');


contourf( ...
    F, ...
    Rr, ...
    Data.understeerGradient, ...
    20);

hold on;

colorbar;


% Aero validity boundary
contour( ...
    F, ...
    Rr, ...
    Data.minimumAeroMargin, ...
    [0 0], ...
    'k', ...
    'LineWidth',2.0);


% Neutral-steer contour, if present
if min(Data.understeerGradient(:),[],'omitnan') <= 0 && ...
        max(Data.understeerGradient(:),[],'omitnan') >= 0

    contour( ...
        F, ...
        Rr, ...
        Data.understeerGradient, ...
        [0 0], ...
        '--k', ...
        'LineWidth',1.5);

end


plot( ...
    baselineFront, ...
    baselineRear, ...
    'kx', ...
    'MarkerSize',12, ...
    'LineWidth',2.0);


grid on;

xlabel('Front Spring Rate [N/mm]');
ylabel('Rear Spring Rate [N/mm]');

title( ...
    'Stage 6.4 - Figure 3 - Vehicle Balance Trade-Off');


%% ============================================================
% FIGURE 4 - FRONT / REAR RIDE-HEIGHT CONSTRAINTS
% ============================================================

figure( ...
    'Name', ...
    'Stage 6.4 - Figure 4 - Spring Trade-Off - Platform Constraints');


contourf( ...
    F, ...
    Rr, ...
    Data.minimumAeroMargin, ...
    20);

hold on;

colorbar;


% Front ride-height boundary
contour( ...
    F, ...
    Rr, ...
    Data.frontAeroMargin, ...
    [0 0], ...
    'k--', ...
    'LineWidth',2.0);


% Rear ride-height boundary
contour( ...
    F, ...
    Rr, ...
    Data.rearAeroMargin, ...
    [0 0], ...
    'k:', ...
    'LineWidth',2.5);


plot( ...
    baselineFront, ...
    baselineRear, ...
    'kx', ...
    'MarkerSize',12, ...
    'LineWidth',2.0);


if ~isnan(Study.maximumValidDownforce)

    plot( ...
        Study.maxDownforceFrontSpring, ...
        Study.maxDownforceRearSpring, ...
        'ko', ...
        'MarkerSize',8, ...
        'LineWidth',2.0);

end


grid on;

xlabel('Front Spring Rate [N/mm]');
ylabel('Rear Spring Rate [N/mm]');

title( ...
    'Stage 6.4 - Figure 4 - Platform Constraint Map');


end