function displaySetupComparison(Comparison)
%DISPLAYSETUPCOMPARISON
%
% Stage 6.2 - Baseline vs Proposed Setup Comparison


B = Comparison.BaselinePerformance.KPI;
P = Comparison.ProposedPerformance.KPI;

C = Comparison.Change;


fprintf('\n');
fprintf('==========================================================================\n');
fprintf(' BASELINE vs PROPOSED SETUP - STAGE 6.2\n');
fprintf('==========================================================================\n');


%% ============================================================
%  SETUP
%  ============================================================

fprintf('\nSETUP CHANGES\n');
fprintf('--------------------------------------------------------------------------\n');
fprintf('                            BASELINE      PROPOSED        CHANGE\n');
fprintf('--------------------------------------------------------------------------\n');

printRow( ...
    'Front Spring [N/mm]', ...
    Comparison.SetupChange.springFront, ...
    1);

printRow( ...
    'Rear Spring [N/mm]', ...
    Comparison.SetupChange.springRear, ...
    1);

printRow( ...
    'Front ARB [N/mm]', ...
    Comparison.SetupChange.arbFront, ...
    1);

printRow( ...
    'Rear ARB [N/mm]', ...
    Comparison.SetupChange.arbRear, ...
    1);

printRow( ...
    'Front Ride Height [mm]', ...
    Comparison.SetupChange.rideHeightFront, ...
    2);

printRow( ...
    'Rear Ride Height [mm]', ...
    Comparison.SetupChange.rideHeightRear, ...
    2);


%% ============================================================
%  LATERAL PERFORMANCE
%  ============================================================

fprintf('\nLATERAL PERFORMANCE\n');
fprintf('--------------------------------------------------------------------------\n');

printRow( ...
    'Lateral Acceleration [g]', ...
    C.lateralAccelerationG, ...
    4);

printRow( ...
    'Yaw Rate [deg/s]', ...
    C.yawRateDeg, ...
    3);

printRow( ...
    'CG Sideslip [deg]', ...
    C.cgSideslipDeg, ...
    4);

printRow( ...
    'Understeer Grad. [deg/g]', ...
    C.understeerGradient, ...
    4);


fprintf('%-27s %12s %13s\n', ...
    'Vehicle Balance', ...
    B.balanceType, ...
    P.balanceType);


%% ============================================================
%  AERODYNAMIC PERFORMANCE
%  ============================================================

fprintf('\nAERODYNAMIC PERFORMANCE\n');
fprintf('--------------------------------------------------------------------------\n');

printRow( ...
    'CL [-]', ...
    C.CL, ...
    4);

printRow( ...
    'CD [-]', ...
    C.CD, ...
    4);

printRow( ...
    'CL/CD [-]', ...
    C.aeroEfficiency, ...
    4);

printRow( ...
    'Downforce [N]', ...
    C.downforce, ...
    1);

printRow( ...
    'Front Aero Balance [%]', ...
    C.aeroBalanceFrontPercent, ...
    2);


%% ============================================================
%  PLATFORM
%  ============================================================

fprintf('\nAERODYNAMIC PLATFORM\n');
fprintf('--------------------------------------------------------------------------\n');

printRow( ...
    'Front Ride Height [mm]', ...
    C.frontRideHeight, ...
    3);

printRow( ...
    'Rear Ride Height [mm]', ...
    C.rearRideHeight, ...
    3);

printRow( ...
    'Front Compression [mm]', ...
    C.frontCompression, ...
    3);

printRow( ...
    'Rear Compression [mm]', ...
    C.rearCompression, ...
    3);

printRow( ...
    'Mean Heave [mm]', ...
    C.heave, ...
    3);

printRow( ...
    'Rake Angle [deg]', ...
    C.rakeAngleDeg, ...
    4);


%% ============================================================
%  SUSPENSION
%  ============================================================

fprintf('\nSUSPENSION\n');
fprintf('--------------------------------------------------------------------------\n');

printRow( ...
    'Front Wheel Rate [N/mm]', ...
    C.frontWheelRate, ...
    2);

printRow( ...
    'Rear Wheel Rate [N/mm]', ...
    C.rearWheelRate, ...
    2);

printRow( ...
    'Total Heave Stiff. [N/mm]', ...
    C.totalHeaveStiffness, ...
    2);


%% ============================================================
%  AERO-MAP MARGIN
%  ============================================================

fprintf('\nAERO-MAP MARGIN\n');
fprintf('--------------------------------------------------------------------------\n');

fprintf('Baseline Minimum Margin : %+10.3f mm\n', ...
    Comparison.Margin.Baseline.minimum);

fprintf('Proposed Minimum Margin : %+10.3f mm\n', ...
    Comparison.Margin.Proposed.minimum);


%% ============================================================
%  MODEL VALIDITY
%  ============================================================

fprintf('\nMODEL VALIDITY\n');
fprintf('--------------------------------------------------------------------------\n');

fprintf('Baseline Overall Status : %s\n', ...
    passFail( ...
    Comparison.Validity.baselineValid));

fprintf('Proposed Overall Status : %s\n', ...
    passFail( ...
    Comparison.Validity.proposedValid));

fprintf('Baseline Aero Map       : %s\n', ...
    passFail( ...
    Comparison.Validity.baselineAeroMapValid));

fprintf('Proposed Aero Map       : %s\n', ...
    passFail( ...
    Comparison.Validity.proposedAeroMapValid));

fprintf('Validity Assessment     : %s\n', ...
    Comparison.Validity.description);


%% ============================================================
%  ENGINEERING CHANGE SUMMARY
%  ============================================================

fprintf('\nENGINEERING CHANGE SUMMARY\n');
fprintf('--------------------------------------------------------------------------\n');

fprintf('Downforce               : %s\n', ...
    Comparison.Indicators.downforceChange);

fprintf('Aero Efficiency         : %s\n', ...
    Comparison.Indicators.aeroEfficiencyChange);

fprintf('Front Ride Height       : %s\n', ...
    Comparison.Indicators.frontRideHeightChange);

fprintf('Rear Ride Height        : %s\n', ...
    Comparison.Indicators.rearRideHeightChange);

fprintf('Mean Heave              : %s\n', ...
    Comparison.Indicators.heaveChange);

fprintf('Understeer Gradient     : %s\n', ...
    Comparison.Indicators.understeerGradientChange);

fprintf('Front Cornering Stiff.  : %s\n', ...
    Comparison.Indicators.frontCorneringStiffnessChange);

fprintf('Rear Cornering Stiff.   : %s\n', ...
    Comparison.Indicators.rearCorneringStiffnessChange);


fprintf('==========================================================================\n');

end


%% ============================================================
%  LOCAL FUNCTION - TABLE ROW
%  ============================================================

function printRow(label, Change, decimals)

formatString = ...
    sprintf( ...
    '%%-27s %%12.%df %%13.%df %%+11.2f%%%%\\n', ...
    decimals, ...
    decimals);

if isnan(Change.percent)

    valueFormat = ...
        sprintf( ...
        '%%-27s %%12.%df %%13.%df %%11s\\n', ...
        decimals, ...
        decimals);

    fprintf( ...
        valueFormat, ...
        label, ...
        Change.baseline, ...
        Change.proposed, ...
        'N/A');

else

    fprintf( ...
        formatString, ...
        label, ...
        Change.baseline, ...
        Change.proposed, ...
        Change.percent);

end

end


%% ============================================================
%  LOCAL FUNCTION - PASS / CHECK
%  ============================================================

function text = passFail(condition)

if condition

    text = 'PASS';

else

    text = 'CHECK';

end

end