function displayVerticalFrequencyResponse(FrequencyResponse)
%DISPLAYVERTICALFREQUENCYRESPONSE
%
% Stage 5.7B - Vertical Frequency Response
%
% Displays the principal results from the harmonic road-input
% frequency-response analysis.
%
% IMPORTANT:
% The natural frequencies reported below come from the undamped
% eigenvalue analysis in Stage 5.7A.
%
% The maximum response frequencies are the frequencies at which
% each road-excited response reaches its global maximum. These
% do not necessarily coincide with the natural frequencies of
% the system.


fprintf('\n');
fprintf('============================================\n');
fprintf(' VERTICAL FREQUENCY RESPONSE - STAGE 5.7B\n');
fprintf('============================================\n');


%% ============================================================
%  ANALYSIS RANGE
%  ============================================================

fprintf('\nANALYSIS RANGE\n');
fprintf('--------------------------------------------\n');

fprintf('Minimum Frequency       : %8.3f Hz\n', ...
    min(FrequencyResponse.frequency));

fprintf('Maximum Frequency       : %8.3f Hz\n', ...
    max(FrequencyResponse.frequency));


%% ============================================================
%  UNDAMPED REFERENCE MODES
%  ============================================================
%
% These frequencies come from the coupled eigenvalue solution
% calculated in Stage 5.7A.
%
% They represent the undamped natural modes of the quarter-car
% system and are used as reference frequencies for interpreting
% the forced-response results.
%

fprintf('\nUNDAMPED REFERENCE MODES\n');
fprintf('--------------------------------------------\n');

fprintf('Body Natural Frequency  : %8.3f Hz\n', ...
    FrequencyResponse.bodyNaturalFrequency);

fprintf('Wheel-Hop Frequency     : %8.3f Hz\n', ...
    FrequencyResponse.wheelHopNaturalFrequency);


%% ============================================================
%  ROAD-EXCITED RESPONSE MAXIMA
%  ============================================================
%
% These are the GLOBAL MAXIMUM responses generated by the
% harmonic road excitation.
%
% They should not automatically be interpreted as natural
% frequencies because damping and base excitation influence
% the location and magnitude of the response maxima.
%

fprintf('\nROAD-EXCITED RESPONSE MAXIMA\n');
fprintf('--------------------------------------------\n');


%% Sprung-Mass Response

fprintf('Maximum Body Response   : %8.3f Hz\n', ...
    FrequencyResponse.bodyPeakFrequency);

fprintf('Body Peak Magnitude     : %8.3f\n', ...
    FrequencyResponse.bodyPeakMagnitude);


fprintf('\n');


%% Unsprung-Mass Response

fprintf('Maximum Wheel Response  : %8.3f Hz\n', ...
    FrequencyResponse.wheelPeakFrequency);

fprintf('Wheel Peak Magnitude    : %8.3f\n', ...
    FrequencyResponse.wheelPeakMagnitude);


fprintf('\n');


%% Dynamic Tyre Load Response

fprintf('Maximum Tyre Load Resp. : %8.3f Hz\n', ...
    FrequencyResponse.tyreLoadPeakFrequency);

fprintf('Tyre Load Sensitivity   : %8.1f N/m\n', ...
    FrequencyResponse.tyreLoadPeak);


%% ============================================================
%  INTERPRETATION
%  ============================================================

fprintf('\nINTERPRETATION\n');
fprintf('--------------------------------------------\n');

fprintf(['Natural frequencies define the system modes,\n' ...
         'while forced-response maxima depend on damping,\n' ...
         'road excitation and the selected response output.\n']);


%% ============================================================
%  END
%  ============================================================

fprintf('============================================\n');

end