function plotVehicleOverview(Vehicle, Setup, Derived)

%PLOTVEHICLEOVERVIEW
%
% Visualise the baseline vehicle geometry and setup.
%
%   plotVehicleOverview(Vehicle, Setup, Derived)
%
%   Displays:
%       1. Top-view vehicle geometry
%       2. Side-view vehicle platform
%       3. Vehicle/setup summary
%
% Website / portfolio layout:
%
%   -----------------------------------------------
%   |          TOP VIEW       |      SIDE VIEW     |
%   -----------------------------------------------
%   |           CURRENT VEHICLE & SETUP            |
%   -----------------------------------------------


%% ============================================================
%  CREATE FIGURE
% ============================================================

fig = figure( ...
    'Name','Vehicle Performance Tool - Vehicle Overview', ...
    'NumberTitle','off', ...
    'Color','w', ...
    'Position',[100 100 1500 850]);


t = tiledlayout(fig,3,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


% Give the plots more space than the setup summary
t.TileSpacing = 'compact';
t.Padding = 'compact';


%% ============================================================
%  TOP VIEW
% ============================================================

ax1 = nexttile(t,1);

hold(ax1,'on');
grid(ax1,'on');
axis(ax1,'equal');

title(ax1, ...
    'Vehicle Geometry - Top View', ...
    'FontWeight','bold');

xlabel(ax1,'Longitudinal Position [m]');
ylabel(ax1,'Lateral Position [m]');


%% ------------------------------------------------------------
% Axle positions
% ------------------------------------------------------------

xFront = 0;
xRear  = Vehicle.wheelbase;

yFront = Vehicle.trackFront / 2;
yRear  = Vehicle.trackRear  / 2;


%% ------------------------------------------------------------
% Vehicle centreline
% ------------------------------------------------------------

plot(ax1, ...
    [-0.3 Vehicle.wheelbase + 0.3], ...
    [0 0], ...
    '--', ...
    'LineWidth',1);


%% ------------------------------------------------------------
% Axle lines
% ------------------------------------------------------------

plot(ax1, ...
    [xFront xFront], ...
    [-yFront yFront], ...
    'LineWidth',2);

plot(ax1, ...
    [xRear xRear], ...
    [-yRear yRear], ...
    'LineWidth',2);


%% ------------------------------------------------------------
% Wheel dimensions
% ------------------------------------------------------------

wheelLength = 0.35;
wheelWidth  = 0.12;


%% ------------------------------------------------------------
% Front Left Wheel
% ------------------------------------------------------------

rectangle(ax1, ...
    'Position',[ ...
    xFront-wheelLength/2, ...
    yFront-wheelWidth/2, ...
    wheelLength, ...
    wheelWidth], ...
    'Curvature',0.15, ...
    'LineWidth',2);


%% ------------------------------------------------------------
% Front Right Wheel
% ------------------------------------------------------------

rectangle(ax1, ...
    'Position',[ ...
    xFront-wheelLength/2, ...
    -yFront-wheelWidth/2, ...
    wheelLength, ...
    wheelWidth], ...
    'Curvature',0.15, ...
    'LineWidth',2);


%% ------------------------------------------------------------
% Rear Left Wheel
% ------------------------------------------------------------

rectangle(ax1, ...
    'Position',[ ...
    xRear-wheelLength/2, ...
    yRear-wheelWidth/2, ...
    wheelLength, ...
    wheelWidth], ...
    'Curvature',0.15, ...
    'LineWidth',2);


%% ------------------------------------------------------------
% Rear Right Wheel
% ------------------------------------------------------------

rectangle(ax1, ...
    'Position',[ ...
    xRear-wheelLength/2, ...
    -yRear-wheelWidth/2, ...
    wheelLength, ...
    wheelWidth], ...
    'Curvature',0.15, ...
    'LineWidth',2);


%% ------------------------------------------------------------
% CG position
% ------------------------------------------------------------

xCG = Derived.cgToFront;

plot(ax1, ...
    xCG,0, ...
    'o', ...
    'MarkerSize',12, ...
    'MarkerFaceColor','auto', ...
    'LineWidth',2);

text(ax1, ...
    xCG,0.14, ...
    'CG', ...
    'HorizontalAlignment','center', ...
    'FontWeight','bold');


%% ------------------------------------------------------------
% Corner load labels
% ------------------------------------------------------------

text(ax1, ...
    xFront, ...
    yFront + 0.18, ...
    sprintf('FL\n%.0f N',Derived.FL), ...
    'HorizontalAlignment','center');

text(ax1, ...
    xFront, ...
    -yFront - 0.18, ...
    sprintf('FR\n%.0f N',Derived.FR), ...
    'HorizontalAlignment','center');

text(ax1, ...
    xRear, ...
    yRear + 0.18, ...
    sprintf('RL\n%.0f N',Derived.RL), ...
    'HorizontalAlignment','center');

text(ax1, ...
    xRear, ...
    -yRear - 0.18, ...
    sprintf('RR\n%.0f N',Derived.RR), ...
    'HorizontalAlignment','center');


%% ------------------------------------------------------------
% CG distance labels
% ------------------------------------------------------------

text(ax1, ...
    Derived.cgToFront/2, ...
    0.08, ...
    sprintf('a = %.2f m',Derived.cgToFront), ...
    'HorizontalAlignment','center');

text(ax1, ...
    Derived.cgToFront + Derived.cgToRear/2, ...
    0.08, ...
    sprintf('b = %.2f m',Derived.cgToRear), ...
    'HorizontalAlignment','center');


%% ------------------------------------------------------------
% Top-view axis limits
% ------------------------------------------------------------

xlim(ax1, ...
    [-0.5 Vehicle.wheelbase + 0.5]);

maxTrack = max( ...
    Vehicle.trackFront, ...
    Vehicle.trackRear);

ylim(ax1,[ ...
    -maxTrack/2 - 0.5, ...
     maxTrack/2 + 0.5]);


%% ============================================================
%  SIDE VIEW - VEHICLE PLATFORM
% ============================================================

ax2 = nexttile(t,2);

hold(ax2,'on');
grid(ax2,'on');

title(ax2, ...
    'Vehicle Platform - Side View', ...
    'FontWeight','bold');

xlabel(ax2,'Longitudinal Position [m]');
ylabel(ax2,'Height [m]');


%% ------------------------------------------------------------
% Ride heights
% ------------------------------------------------------------

RHFront = Setup.rideHeightFront / 1000;
RHRear  = Setup.rideHeightRear  / 1000;


%% ------------------------------------------------------------
% Ground reference
% ------------------------------------------------------------

plot(ax2, ...
    [-0.35 Vehicle.wheelbase + 0.35], ...
    [0 0], ...
    'k-', ...
    'LineWidth',1.5);


%% ------------------------------------------------------------
% Axle reference markers
% ------------------------------------------------------------

% The vertical axis is intentionally exaggerated to make small
% ride-height and platform changes visible.
%
% Therefore physical tyre geometry is not shown to scale.

axleMarkerWidth  = 0.08;
axleMarkerHeight = 0.08;


% Front axle marker

rectangle(ax2, ...
    'Position',[ ...
    -axleMarkerWidth/2, ...
    0, ...
    axleMarkerWidth, ...
    axleMarkerHeight], ...
    'Curvature',0.15, ...
    'FaceColor',[0.20 0.20 0.20], ...
    'EdgeColor',[0.20 0.20 0.20]);


% Rear axle marker

rectangle(ax2, ...
    'Position',[ ...
    Vehicle.wheelbase-axleMarkerWidth/2, ...
    0, ...
    axleMarkerWidth, ...
    axleMarkerHeight], ...
    'Curvature',0.15, ...
    'FaceColor',[0.20 0.20 0.20], ...
    'EdgeColor',[0.20 0.20 0.20]);


%% ------------------------------------------------------------
% Vehicle platform
% ------------------------------------------------------------

plot(ax2, ...
    [0 Vehicle.wheelbase], ...
    [RHFront RHRear], ...
    'LineWidth',3);


%% ------------------------------------------------------------
% Front ride-height point
% ------------------------------------------------------------

plot(ax2, ...
    0, ...
    RHFront, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','w', ...
    'LineWidth',1.5);


%% ------------------------------------------------------------
% Rear ride-height point
% ------------------------------------------------------------

plot(ax2, ...
    Vehicle.wheelbase, ...
    RHRear, ...
    'o', ...
    'MarkerSize',7, ...
    'MarkerFaceColor','w', ...
    'LineWidth',1.5);


%% ------------------------------------------------------------
% Ride-height reference lines
% ------------------------------------------------------------

plot(ax2, ...
    [0 0], ...
    [0 RHFront], ...
    ':', ...
    'LineWidth',1.2);

plot(ax2, ...
    [Vehicle.wheelbase Vehicle.wheelbase], ...
    [0 RHRear], ...
    ':', ...
    'LineWidth',1.2);


%% ------------------------------------------------------------
% Front ride-height label
% ------------------------------------------------------------

text(ax2, ...
    0.15, ...
    RHFront + 0.035, ...
    sprintf('RH_F = %.0f mm', ...
    Setup.rideHeightFront), ...
    'HorizontalAlignment','left', ...
    'VerticalAlignment','bottom', ...
    'FontSize',9);


%% ------------------------------------------------------------
% Rear ride-height label
% ------------------------------------------------------------

text(ax2, ...
    Vehicle.wheelbase - 0.15, ...
    RHRear + 0.035, ...
    sprintf('RH_R = %.0f mm', ...
    Setup.rideHeightRear), ...
    'HorizontalAlignment','right', ...
    'VerticalAlignment','bottom', ...
    'FontSize',9);


%% ------------------------------------------------------------
% CG marker
% ------------------------------------------------------------

plot(ax2, ...
    Derived.cgToFront, ...
    Vehicle.cgHeight, ...
    'o', ...
    'MarkerSize',10, ...
    'MarkerFaceColor','auto', ...
    'LineWidth',1.5);


%% ------------------------------------------------------------
% CG height reference
% ------------------------------------------------------------

plot(ax2, ...
    [Derived.cgToFront Derived.cgToFront], ...
    [0 Vehicle.cgHeight], ...
    '--', ...
    'LineWidth',1);


%% ------------------------------------------------------------
% CG label
% ------------------------------------------------------------

text(ax2, ...
    Derived.cgToFront, ...
    Vehicle.cgHeight + 0.055, ...
    sprintf('CG   h_{CG} = %.2f m', ...
    Vehicle.cgHeight), ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','bottom', ...
    'FontWeight','bold', ...
    'FontSize',9);


%% ------------------------------------------------------------
% Longitudinal CG position
% ------------------------------------------------------------

text(ax2, ...
    Derived.cgToFront, ...
    Vehicle.cgHeight - 0.055, ...
    sprintf('x_{CG} = %.2f m', ...
    Derived.cgToFront), ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',8);


%% ------------------------------------------------------------
% Rake annotation
% ------------------------------------------------------------

text(ax2, ...
    Vehicle.wheelbase/2, ...
    -0.030, ...
    sprintf('\\theta_{rake} = %.3f^\\circ', ...
    Derived.rakeAngleDeg), ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',9);


%% ------------------------------------------------------------
% Axle labels
% ------------------------------------------------------------

text(ax2, ...
    0, ...
    -0.060, ...
    'Front Axle', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',8);

text(ax2, ...
    Vehicle.wheelbase, ...
    -0.060, ...
    'Rear Axle', ...
    'HorizontalAlignment','center', ...
    'VerticalAlignment','top', ...
    'FontSize',8);


%% ------------------------------------------------------------
% Side-view axis limits
% ------------------------------------------------------------

xlim(ax2,[ ...
    -0.35 ...
    Vehicle.wheelbase + 0.35]);

ylim(ax2,[ ...
    -0.10 ...
    max(0.50,Vehicle.cgHeight + 0.15)]);


%% ============================================================
%  VEHICLE / SETUP SUMMARY
% ============================================================

ax3 = nexttile(t,3,[1 2]);

axis(ax3,'off');

title(ax3, ...
    'Current Vehicle & Setup', ...
    'FontWeight','bold');


%% ============================================================
%  SUMMARY - FOUR COLUMN WEBSITE LAYOUT
% ============================================================

% ------------------------------------------------------------
% Column positions
% ------------------------------------------------------------

x1 = 0.04;
x2 = 0.29;
x3 = 0.54;
x4 = 0.79;

yTitle = 0.78;
y1 = 0.57;
y2 = 0.40;
y3 = 0.23;
y4 = 0.06;


%% ------------------------------------------------------------
% VEHICLE
% ------------------------------------------------------------

text(ax3,x1,yTitle, ...
    'VEHICLE', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',10);

text(ax3,x1,y1, ...
    sprintf('Mass                 %.1f kg', ...
    Vehicle.mass), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x1,y2, ...
    sprintf('Front Weight Dist.   %.1f %%', ...
    Vehicle.frontWeightDistribution*100), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x1,y3, ...
    sprintf('CG Height            %.3f m', ...
    Vehicle.cgHeight), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x1,y4, ...
    sprintf('Wheelbase            %.3f m', ...
    Vehicle.wheelbase), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);


%% ------------------------------------------------------------
% SUSPENSION
% ------------------------------------------------------------

text(ax3,x2,yTitle, ...
    'SUSPENSION', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',10);

text(ax3,x2,y1, ...
    sprintf('Front Spring         %.1f N/mm', ...
    Setup.springFront), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x2,y2, ...
    sprintf('Rear Spring          %.1f N/mm', ...
    Setup.springRear), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x2,y3, ...
    sprintf('Front Wheel Rate     %.1f N/mm', ...
    Derived.springWheelRateFront), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x2,y4, ...
    sprintf('Rear Wheel Rate      %.1f N/mm', ...
    Derived.springWheelRateRear), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);


%% ------------------------------------------------------------
% PLATFORM
% ------------------------------------------------------------

text(ax3,x3,yTitle, ...
    'PLATFORM', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',10);

text(ax3,x3,y1, ...
    sprintf('Front Ride Height    %.1f mm', ...
    Setup.rideHeightFront), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x3,y2, ...
    sprintf('Rear Ride Height     %.1f mm', ...
    Setup.rideHeightRear), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x3,y3, ...
    sprintf('Ride Height Delta    %.1f mm', ...
    Derived.rideHeightDelta), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x3,y4, ...
    sprintf('Rake                 %.3f deg', ...
    Derived.rakeAngleDeg), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);


%% ------------------------------------------------------------
% ALIGNMENT
% ------------------------------------------------------------

text(ax3,x4,yTitle, ...
    'ALIGNMENT', ...
    'Units','normalized', ...
    'FontWeight','bold', ...
    'FontSize',10);

text(ax3,x4,y1, ...
    sprintf('Front Camber         %.2f deg', ...
    Setup.camberFront), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x4,y2, ...
    sprintf('Rear Camber          %.2f deg', ...
    Setup.camberRear), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x4,y3, ...
    sprintf('Front Toe            %.2f deg', ...
    Setup.toeFront), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);

text(ax3,x4,y4, ...
    sprintf('Rear Toe             %.2f deg', ...
    Setup.toeRear), ...
    'Units','normalized', ...
    'FontName','Consolas', ...
    'FontSize',9);


%% ============================================================
%  FIGURE TITLE
% ============================================================

sgtitle(t, ...
    'Vehicle & Setup Architecture', ...
    'FontWeight','bold', ...
    'FontSize',15);


end