function VehiclePerfromanceDashboard( ...
    Vehicle, ...
    Setup, ...
    Operating, ...
    Tyre, ...
    Constants, ...
    AeroMap)
%VEHICLEPERFROMANCEDASHBOARD
%
% Stage 6.5F - Final Interactive Vehicle Performance Dashboard
%
% Features:
%   - User-defined setup inputs
%   - Integrated vehicle-performance calculation
%   - Baseline vs current KPI comparison
%   - Aero-map margins
%   - Vehicle balance classification
%   - Model validity display
%   - 2D front/rear spring trade-off map
%   - Downforce contour field
%   - Aero-platform validity boundary
%   - Baseline / current setup markers
%   - Maximum valid downforce point within tested grid
%   - Rule-based engineering interpretation of setup changes
%   - Model-scope notes and final validity warnings
%
% IMPORTANT:
%   The GUI contains no vehicle physics.
%   All calculations use the validated project functions.
%% ============================================================
% COLOURS
% ============================================================
Colours.background = [0.96 0.97 0.98];
Colours.panel      = [1.00 1.00 1.00];
Colours.dark       = [0.10 0.12 0.15];
Colours.text       = [0.18 0.20 0.23];
Colours.muted      = [0.42 0.45 0.50];
Colours.accent     = [0.12 0.38 0.62];
Colours.pass       = [0.18 0.55 0.30];
Colours.warning    = [0.85 0.52 0.12];
Colours.fail       = [0.75 0.18 0.18];
%% ============================================================
% BASELINE
% ============================================================
BaselineSetup = Setup;
%% ============================================================
% TRADE-OFF MAP SETTINGS
% ============================================================
frontSpringValues = 100:5:220;
rearSpringValues  = 90:5:200;
CachedTradeoffStudy = [];
CachedTradeoffSpeed = NaN;
%% ============================================================
% MAIN WINDOW
% ============================================================
fig = uifigure( ...
    'Name', ...
    'Vehicle Performance Setup & Sensitivity Tool', ...
    'Position', ...
    [60 20 1500 980], ...
    'Color', ...
    Colours.background);
%% ============================================================
% MAIN GRID
% ============================================================
mainGrid = uigridlayout(fig,[3 2]);
mainGrid.RowHeight = {75,'1x',55};
mainGrid.ColumnWidth = {360,'1x'};
mainGrid.Padding = [18 18 18 18];
mainGrid.RowSpacing = 14;
mainGrid.ColumnSpacing = 14;
%% ============================================================
% HEADER
% ============================================================
headerPanel = uipanel(mainGrid);
headerPanel.Layout.Row = 1;
headerPanel.Layout.Column = [1 2];
headerPanel.BackgroundColor = Colours.background;
headerPanel.BorderType = 'none';
headerGrid = uigridlayout(headerPanel,[2 2]);
headerGrid.RowHeight = {36,22};
headerGrid.ColumnWidth = {'1x',260};
headerGrid.Padding = [18 8 18 6];
headerGrid.RowSpacing = 0;
titleLabel = uilabel(headerGrid);
titleLabel.Layout.Row = 1;
titleLabel.Layout.Column = 1;
titleLabel.Text = ...
    'VEHICLE PERFORMANCE SETUP TOOL';
titleLabel.FontSize = 22;
titleLabel.FontWeight = 'bold';
% Keep title black
titleLabel.FontColor = [0 0 0];
subtitleLabel = uilabel(headerGrid);
subtitleLabel.Layout.Row = 2;
subtitleLabel.Layout.Column = 1;
subtitleLabel.Text = ...
    'Integrated setup, aerodynamic platform and vehicle balance analysis';
subtitleLabel.FontSize = 12;
subtitleLabel.FontColor = [0.25 0.25 0.25];
stageLabel = uilabel(headerGrid);
stageLabel.Layout.Row = [1 2];
stageLabel.Layout.Column = 2;
stageLabel.Text = 'STAGE 6.5';
stageLabel.HorizontalAlignment = 'right';
stageLabel.VerticalAlignment = 'center';
stageLabel.FontSize = 15;
stageLabel.FontWeight = 'bold';
stageLabel.FontColor = Colours.accent;
%% ============================================================
% LEFT CONTROL PANEL
% ============================================================
controlPanel = uipanel(mainGrid);
controlPanel.Layout.Row = 2;
controlPanel.Layout.Column = 1;
controlPanel.Title = 'SETUP INPUTS';
controlPanel.FontWeight = 'bold';
controlPanel.FontSize = 13;
controlPanel.BackgroundColor = Colours.panel;
controlGrid = uigridlayout(controlPanel,[14 2]);
controlGrid.ColumnWidth = {'1x',120};
controlGrid.RowHeight = ...
    {28,38,38,28,38,38,28,38,38,28,38,38,46,46};
controlGrid.Padding = [14 12 14 14];
controlGrid.RowSpacing = 6;
%% ------------------------------------------------------------
% SPRING STIFFNESS
% ------------------------------------------------------------
springHeading = uilabel(controlGrid);
springHeading.Layout.Row = 1;
springHeading.Layout.Column = [1 2];
springHeading.Text = 'SPRING STIFFNESS';
springHeading.FontWeight = 'bold';
springHeading.FontColor = Colours.accent;
createInputLabel(controlGrid,'Front Spring [N/mm]',2);
frontSpringField = uieditfield(controlGrid,'numeric');
frontSpringField.Layout.Row = 2;
frontSpringField.Layout.Column = 2;
frontSpringField.Value = Setup.springFront;
frontSpringField.Limits = [50 300];
createInputLabel(controlGrid,'Rear Spring [N/mm]',3);
rearSpringField = uieditfield(controlGrid,'numeric');
rearSpringField.Layout.Row = 3;
rearSpringField.Layout.Column = 2;
rearSpringField.Value = Setup.springRear;
rearSpringField.Limits = [50 300];
%% ------------------------------------------------------------
% ANTI-ROLL BAR
% ------------------------------------------------------------
arbHeading = uilabel(controlGrid);
arbHeading.Layout.Row = 4;
arbHeading.Layout.Column = [1 2];
arbHeading.Text = 'ANTI-ROLL BAR';
arbHeading.FontWeight = 'bold';
arbHeading.FontColor = Colours.accent;
createInputLabel(controlGrid,'Front ARB [N/mm]',5);
frontARBField = uieditfield(controlGrid,'numeric');
frontARBField.Layout.Row = 5;
frontARBField.Layout.Column = 2;
frontARBField.Value = Setup.arbFront;
frontARBField.Limits = [0 100];
createInputLabel(controlGrid,'Rear ARB [N/mm]',6);
rearARBField = uieditfield(controlGrid,'numeric');
rearARBField.Layout.Row = 6;
rearARBField.Layout.Column = 2;
rearARBField.Value = Setup.arbRear;
rearARBField.Limits = [0 100];
%% ------------------------------------------------------------
% STATIC PLATFORM
% ------------------------------------------------------------
platformHeading = uilabel(controlGrid);
platformHeading.Layout.Row = 7;
platformHeading.Layout.Column = [1 2];
platformHeading.Text = 'STATIC PLATFORM';
platformHeading.FontWeight = 'bold';
platformHeading.FontColor = Colours.accent;
createInputLabel(controlGrid,'Front Ride Height [mm]',8);
frontRHField = uieditfield(controlGrid,'numeric');
frontRHField.Layout.Row = 8;
frontRHField.Layout.Column = 2;
frontRHField.Value = Setup.rideHeightFront;
frontRHField.Limits = [10 100];
createInputLabel(controlGrid,'Rear Ride Height [mm]',9);
rearRHField = uieditfield(controlGrid,'numeric');
rearRHField.Layout.Row = 9;
rearRHField.Layout.Column = 2;
rearRHField.Value = Setup.rideHeightRear;
rearRHField.Limits = [10 120];
%% ------------------------------------------------------------
% OPERATING CONDITION
% ------------------------------------------------------------
operatingHeading = uilabel(controlGrid);
operatingHeading.Layout.Row = 10;
operatingHeading.Layout.Column = [1 2];
operatingHeading.Text = 'OPERATING CONDITION';
operatingHeading.FontWeight = 'bold';
operatingHeading.FontColor = Colours.accent;
createInputLabel(controlGrid,'Vehicle Speed [km/h]',11);
speedField = uieditfield(controlGrid,'numeric');
speedField.Layout.Row = 11;
speedField.Layout.Column = 2;
speedField.Value = Operating.speed * 3.6;
speedField.Limits = [0 350];
createInputLabel(controlGrid,'Steering Angle [deg]',12);
steerAngleField = uieditfield(controlGrid,'numeric');
steerAngleField.Layout.Row = 12;
steerAngleField.Layout.Column = 2;
steerAngleField.Value = Operating.steerAngle;
steerAngleField.Limits = [-20 20];
%% ------------------------------------------------------------
% BUTTONS
% ------------------------------------------------------------
runButton = uibutton(controlGrid,'push');
runButton.Layout.Row = 13;
runButton.Layout.Column = [1 2];
runButton.Text = 'RUN ANALYSIS';
runButton.FontSize = 13;
runButton.FontWeight = 'bold';
runButton.BackgroundColor = Colours.accent;
runButton.FontColor = [1 1 1];
resetButton = uibutton(controlGrid,'push');
resetButton.Layout.Row = 14;
resetButton.Layout.Column = [1 2];
resetButton.Text = 'RESET BASELINE';
resetButton.FontSize = 12;
resetButton.FontWeight = 'bold';
%% ============================================================
% RIGHT DASHBOARD
% ============================================================
dashboardPanel = uipanel(mainGrid);
dashboardPanel.Layout.Row = 2;
dashboardPanel.Layout.Column = 2;
dashboardPanel.BackgroundColor = Colours.background;
dashboardPanel.BorderType = 'none';
dashboardGrid = uigridlayout(dashboardPanel,[3 1]);
dashboardGrid.RowHeight = {270,'1x',140};
dashboardGrid.Padding = [0 0 0 0];
dashboardGrid.RowSpacing = 14;
%% ============================================================
% KPI CARDS
% ============================================================
kpiGrid = uigridlayout(dashboardGrid,[1 3]);
kpiGrid.Layout.Row = 1;
kpiGrid.ColumnWidth = {'1x','1x','1x'};
kpiGrid.ColumnSpacing = 12;
kpiGrid.Padding = [0 0 0 0];
%% ------------------------------------------------------------
% PERFORMANCE CARD
% ------------------------------------------------------------
performancePanel = uipanel(kpiGrid);
performancePanel.Layout.Column = 1;
performancePanel.Title = 'PERFORMANCE';
performancePanel.FontWeight = 'bold';
performancePanel.BackgroundColor = Colours.panel;
performanceGrid = uigridlayout(performancePanel,[6 3]);
performanceGrid.ColumnWidth = {'1x',95,80};
performanceGrid.RowHeight = ...
    {'1x','1x','1x','1x','1x','1x'};
performanceGrid.Padding = [10 6 10 8];
[downforceValue,downforceDelta] = ...
    createKPIRow( ...
    performanceGrid,1, ...
    'Downforce','--- N','---');
[efficiencyValue,efficiencyDelta] = ...
    createKPIRow( ...
    performanceGrid,2, ...
    'CL / CD','---','---');
[aeroBalanceValue,aeroBalanceDelta] = ...
    createKPIRow( ...
    performanceGrid,3, ...
    'Aero Balance','--- %','---');
[lateralAccelValue,lateralAccelDelta] = ...
    createKPIRow( ...
    performanceGrid,4, ...
    'Lateral Response','--- g','---');
[understeerValue,understeerDelta] = ...
    createKPIRow( ...
    performanceGrid,5, ...
    'Understeer Grad.','---','---');
balanceLabel = uilabel(performanceGrid);
balanceLabel.Layout.Row = 6;
balanceLabel.Layout.Column = 1;
balanceLabel.Text = 'Balance';
balanceLabel.FontSize = 11;
balanceValue = uilabel(performanceGrid);
balanceValue.Layout.Row = 6;
balanceValue.Layout.Column = [2 3];
balanceValue.Text = '---';
balanceValue.HorizontalAlignment = 'right';
balanceValue.FontWeight = 'bold';
balanceValue.FontColor = Colours.muted;
%% ------------------------------------------------------------
% AERODYNAMIC PLATFORM CARD
% ------------------------------------------------------------
platformPanel = uipanel(kpiGrid);
platformPanel.Layout.Column = 2;
platformPanel.Title = 'AERODYNAMIC PLATFORM';
platformPanel.FontWeight = 'bold';
platformPanel.BackgroundColor = Colours.panel;
platformGrid = uigridlayout(platformPanel,[7 3]);
platformGrid.ColumnWidth = {'1x',95,80};
platformGrid.RowHeight = ...
    {'1x','1x','1x','1x','1x','1x','1x'};
platformGrid.Padding = [10 6 10 8];
[frontRHValue,frontRHDelta] = ...
    createKPIRow( ...
    platformGrid,1, ...
    'Front RH','--- mm','---');
[rearRHValue,rearRHDelta] = ...
    createKPIRow( ...
    platformGrid,2, ...
    'Rear RH','--- mm','---');
[frontCompressionValue,frontCompressionDelta] = ...
    createKPIRow( ...
    platformGrid,3, ...
    'Front Compression','--- mm','---');
[rearCompressionValue,rearCompressionDelta] = ...
    createKPIRow( ...
    platformGrid,4, ...
    'Rear Compression','--- mm','---');
[rakeValue,rakeDelta] = ...
    createKPIRow( ...
    platformGrid,5, ...
    'Rake','--- deg','---');
frontMarginLabel = uilabel(platformGrid);
frontMarginLabel.Layout.Row = 6;
frontMarginLabel.Layout.Column = 1;
frontMarginLabel.Text = 'Front Map Margin';
frontMarginLabel.FontSize = 11;
frontMarginValue = uilabel(platformGrid);
frontMarginValue.Layout.Row = 6;
frontMarginValue.Layout.Column = [2 3];
frontMarginValue.Text = '--- mm';
frontMarginValue.HorizontalAlignment = 'right';
frontMarginValue.FontWeight = 'bold';
rearMarginLabel = uilabel(platformGrid);
rearMarginLabel.Layout.Row = 7;
rearMarginLabel.Layout.Column = 1;
rearMarginLabel.Text = 'Rear Map Margin';
rearMarginLabel.FontSize = 11;
rearMarginValue = uilabel(platformGrid);
rearMarginValue.Layout.Row = 7;
rearMarginValue.Layout.Column = [2 3];
rearMarginValue.Text = '--- mm';
rearMarginValue.HorizontalAlignment = 'right';
rearMarginValue.FontWeight = 'bold';
%% ------------------------------------------------------------
% MODEL STATUS CARD
% ------------------------------------------------------------
statusPanel = uipanel(kpiGrid);
statusPanel.Layout.Column = 3;
statusPanel.Title = 'MODEL STATUS';
statusPanel.FontWeight = 'bold';
statusPanel.BackgroundColor = Colours.panel;
statusGrid = uigridlayout(statusPanel,[5 2]);
statusGrid.ColumnWidth = {'1x',85};
statusGrid.RowHeight = ...
    {'1x','1x','1x','1x','1x'};
statusGrid.Padding = [12 8 12 10];
aeroStatusValue = ...
    createStatusRow(statusGrid,1,'Aero Map');
platformStatusValue = ...
    createStatusRow(statusGrid,2,'Platform Solver');
lateralStatusValue = ...
    createStatusRow(statusGrid,3,'Lateral Solver');
verticalStatusValue = ...
    createStatusRow(statusGrid,4,'Vertical Load');
overallStatusValue = ...
    createStatusRow(statusGrid,5,'Overall');
%% ============================================================
% SETUP TRADE-OFF MAP
% ============================================================
plotPanel = uipanel(dashboardGrid);
plotPanel.Layout.Row = 2;
plotPanel.Title = 'SETUP TRADE-OFF MAP';
plotPanel.FontWeight = 'bold';
plotPanel.BackgroundColor = Colours.panel;
plotGrid = uigridlayout(plotPanel,[1 1]);
plotGrid.Padding = [12 8 12 12];
analysisAxes = uiaxes(plotGrid);
analysisAxes.Box = 'on';
analysisAxes.XGrid = 'on';
analysisAxes.YGrid = 'on';
title( ...
    analysisAxes, ...
    'Front / Rear Spring Trade-Off');
xlabel( ...
    analysisAxes, ...
    'Front Spring Rate [N/mm]');
ylabel( ...
    analysisAxes, ...
    'Rear Spring Rate [N/mm]');
xlim(analysisAxes,[100 220]);
ylim(analysisAxes,[90 200]);
%% ============================================================
% ENGINEERING INTERPRETATION
% ============================================================
interpretationPanel = uipanel(dashboardGrid);
interpretationPanel.Layout.Row = 3;
interpretationPanel.Title = 'ENGINEERING INTERPRETATION';
interpretationPanel.FontWeight = 'bold';
interpretationPanel.BackgroundColor = Colours.panel;
interpretationGrid = uigridlayout(interpretationPanel,[6 2]);
interpretationGrid.ColumnWidth = {95,'1x'};
interpretationGrid.RowHeight = {'1x','1x','1x','1x','1x','1x'};
interpretationGrid.Padding = [12 5 12 6];
interpretationGrid.RowSpacing = 2;
platformInterpretation = createInterpretationRow( ...
    interpretationGrid,1,'PLATFORM',Colours.accent);
aeroInterpretation = createInterpretationRow( ...
    interpretationGrid,2,'AERO',Colours.accent);
balanceInterpretation = createInterpretationRow( ...
    interpretationGrid,3,'BALANCE',Colours.accent);
assessmentInterpretation = createInterpretationRow( ...
    interpretationGrid,4,'ASSESSMENT',Colours.accent);
lateralModelNote = createInterpretationRow( ...
    interpretationGrid,5,'MODEL NOTE',Colours.muted);
lateralModelNote.Text = ...
    'Lateral response is linear steady-state response to the prescribed steering input; tyre saturation is not modelled.';
lateralModelNote.FontColor = Colours.muted;
mapScopeNote = createInterpretationRow( ...
    interpretationGrid,6,'MAP NOTE',Colours.muted);
mapScopeNote.Text = ...
    'Max Valid DF is the maximum valid downforce within the tested spring-rate grid; it is not an optimised setup.';
mapScopeNote.FontColor = Colours.muted;
%% ============================================================
% FOOTER
% ============================================================
footerPanel = uipanel(mainGrid);
footerPanel.Layout.Row = 3;
footerPanel.Layout.Column = [1 2];
footerPanel.BackgroundColor = Colours.panel;
footerGrid = uigridlayout(footerPanel,[1 2]);
footerGrid.ColumnWidth = {'1x',260};
footerGrid.Padding = [12 4 12 4];
footerText = uilabel(footerGrid);
footerText.Text = ...
    ['Generic vehicle-performance model | ' ...
     'Setup → Tyres → Balance → Aero → Platform'];
footerText.FontColor = Colours.muted;
modelStateLabel = uilabel(footerGrid);
modelStateLabel.Layout.Column = 2;
modelStateLabel.Text = 'MODEL NOT YET RUN';
modelStateLabel.HorizontalAlignment = 'right';
modelStateLabel.FontWeight = 'bold';
modelStateLabel.FontColor = Colours.warning;
%% ============================================================
% INITIAL PLOT
% ============================================================
plotInitialState();
%% ============================================================
% CALLBACKS
% ============================================================
runButton.ButtonPushedFcn = ...
    @(src,event) runAnalysis();
resetButton.ButtonPushedFcn = ...
    @(src,event) resetBaseline();
%% ============================================================
% RUN ANALYSIS
% ============================================================
    function runAnalysis()
        try
            %% ------------------------------------------------
            % CURRENT SETUP
            % -------------------------------------------------
            CurrentSetup = Setup;
            CurrentOperating = Operating;
            CurrentSetup.springFront = ...
                frontSpringField.Value;
            CurrentSetup.springRear = ...
                rearSpringField.Value;
            CurrentSetup.arbFront = ...
                frontARBField.Value;
            CurrentSetup.arbRear = ...
                rearARBField.Value;
            CurrentSetup.rideHeightFront = ...
                frontRHField.Value;
            CurrentSetup.rideHeightRear = ...
                rearRHField.Value;
            CurrentOperating.speed = ...
                speedField.Value / 3.6;
            CurrentOperating.steerAngle = ...
                steerAngleField.Value;
            modelStateLabel.Text = ...
                'CALCULATING...';
            modelStateLabel.FontColor = ...
                Colours.warning;
            drawnow;
            %% ------------------------------------------------
            % CURRENT PERFORMANCE
            % -------------------------------------------------
            CurrentPerformance = ...
                evaluateVehiclePerformance( ...
                Vehicle, ...
                CurrentSetup, ...
                CurrentOperating, ...
                Tyre, ...
                Constants, ...
                AeroMap);
            %% ------------------------------------------------
            % BASELINE PERFORMANCE
            %
            % Evaluated at the SAME operating condition so that
            % the displayed deltas represent setup effects.
            % -------------------------------------------------
            BaselinePerformance = ...
                evaluateVehiclePerformance( ...
                Vehicle, ...
                BaselineSetup, ...
                CurrentOperating, ...
                Tyre, ...
                Constants, ...
                AeroMap);
            KPI = CurrentPerformance.KPI;
            Status = CurrentPerformance.Status;
            BaseKPI = BaselinePerformance.KPI;
            %% =================================================
            % PERFORMANCE VALUES
            % ==================================================
            downforceValue.Text = ...
                sprintf('%.1f N',KPI.downforce);
            efficiencyValue.Text = ...
                sprintf('%.3f',KPI.aeroEfficiency);
            aeroBalanceValue.Text = ...
                sprintf( ...
                '%.2f %%', ...
                KPI.aeroBalanceFrontPercent);
            lateralAccelValue.Text = ...
                sprintf( ...
                '%+.3f g', ...
                KPI.lateralAccelerationG);
            understeerValue.Text = ...
                sprintf( ...
                '%+.4f', ...
                KPI.understeerGradient);
            %% =================================================
            % PERFORMANCE DELTAS
            % ==================================================
            downforceDelta.Text = ...
                sprintf( ...
                '%+.1f N', ...
                KPI.downforce - ...
                BaseKPI.downforce);
            if abs(BaseKPI.aeroEfficiency) > eps
                efficiencyChangePercent = ...
                    100 * ...
                    (KPI.aeroEfficiency - ...
                    BaseKPI.aeroEfficiency) / ...
                    BaseKPI.aeroEfficiency;
            else
                efficiencyChangePercent = NaN;
            end
            efficiencyDelta.Text = ...
                sprintf( ...
                '%+.2f %%', ...
                efficiencyChangePercent);
            aeroBalanceDelta.Text = ...
                sprintf( ...
                '%+.2f %%', ...
                KPI.aeroBalanceFrontPercent - ...
                BaseKPI.aeroBalanceFrontPercent);
            lateralAccelDelta.Text = ...
                sprintf( ...
                '%+.4f g', ...
                KPI.lateralAccelerationG - ...
                BaseKPI.lateralAccelerationG);
            understeerDelta.Text = ...
                sprintf( ...
                '%+.4f', ...
                KPI.understeerGradient - ...
                BaseKPI.understeerGradient);
            %% =================================================
            % VEHICLE BALANCE CLASSIFICATION
            % ==================================================
            balanceTolerance = 0.002;
            if KPI.understeerGradient > balanceTolerance
                balanceValue.Text = ...
                    'UNDERSTEER';
                balanceValue.FontColor = ...
                    Colours.warning;
            elseif KPI.understeerGradient < -balanceTolerance
                balanceValue.Text = ...
                    'OVERSTEER';
                balanceValue.FontColor = ...
                    Colours.warning;
            else
                balanceValue.Text = ...
                    'NEAR NEUTRAL';
                balanceValue.FontColor = ...
                    Colours.pass;
            end
            %% =================================================
            % PLATFORM VALUES
            % ==================================================
            frontRHValue.Text = ...
                sprintf( ...
                '%.3f mm', ...
                KPI.frontRideHeight);
            rearRHValue.Text = ...
                sprintf( ...
                '%.3f mm', ...
                KPI.rearRideHeight);
            frontCompressionValue.Text = ...
                sprintf( ...
                '%.3f mm', ...
                KPI.frontCompression);
            rearCompressionValue.Text = ...
                sprintf( ...
                '%.3f mm', ...
                KPI.rearCompression);
            rakeValue.Text = ...
                sprintf( ...
                '%.4f deg', ...
                KPI.rakeAngleDeg);
            %% =================================================
            % PLATFORM DELTAS
            % ==================================================
            frontRHDelta.Text = ...
                sprintf( ...
                '%+.3f', ...
                KPI.frontRideHeight - ...
                BaseKPI.frontRideHeight);
            rearRHDelta.Text = ...
                sprintf( ...
                '%+.3f', ...
                KPI.rearRideHeight - ...
                BaseKPI.rearRideHeight);
            frontCompressionDelta.Text = ...
                sprintf( ...
                '%+.3f', ...
                KPI.frontCompression - ...
                BaseKPI.frontCompression);
            rearCompressionDelta.Text = ...
                sprintf( ...
                '%+.3f', ...
                KPI.rearCompression - ...
                BaseKPI.rearCompression);
            rakeDelta.Text = ...
                sprintf( ...
                '%+.4f', ...
                KPI.rakeAngleDeg - ...
                BaseKPI.rakeAngleDeg);
            %% =================================================
            % AERO-MAP MARGINS
            %
            % Validated Stage 4 map limits:
            %
            % Front RH >= 15 mm
            % Rear RH  >= 30 mm
            % ==================================================
            frontMinimumRH = 15;
            rearMinimumRH  = 30;
            frontMargin = ...
                KPI.frontRideHeight - ...
                frontMinimumRH;
            rearMargin = ...
                KPI.rearRideHeight - ...
                rearMinimumRH;
            frontMarginValue.Text = ...
                sprintf( ...
                '%+.3f mm', ...
                frontMargin);
            rearMarginValue.Text = ...
                sprintf( ...
                '%+.3f mm', ...
                rearMargin);
            setMarginColour( ...
                frontMarginValue, ...
                frontMargin);
            setMarginColour( ...
                rearMarginValue, ...
                rearMargin);
            %% =================================================
            % MODEL STATUS
            % ==================================================
            setStatus( ...
                aeroStatusValue, ...
                Status.aeroMapValid);
            setStatus( ...
                platformStatusValue, ...
                Status.platformConverged);
            setStatus( ...
                lateralStatusValue, ...
                Status.lateralSolverConverged);
            setStatus( ...
                verticalStatusValue, ...
                Status.verticalLoadValid);
            setStatus( ...
                overallStatusValue, ...
                Status.allValid);
            %% =================================================
            % ENGINEERING INTERPRETATION
            % ==================================================
            updateEngineeringInterpretation( ...
                KPI, ...
                BaseKPI, ...
                Status, ...
                BaselinePerformance.Status, ...
                CurrentOperating, ...
                frontMinimumRH, ...
                rearMinimumRH);
            %% =================================================
            % UPDATE TRADE-OFF MAP
            % ==================================================
            updateTradeoffMap( ...
                CurrentSetup, ...
                CurrentOperating);
            %% =================================================
            % OVERALL MODEL STATE
            % ==================================================
            if Status.allValid
                modelStateLabel.Text = ...
                    'MODEL STATUS: PASS';
                modelStateLabel.FontColor = ...
                    Colours.pass;
            else
                modelStateLabel.Text = ...
                    'MODEL STATUS: CHECK';
                modelStateLabel.FontColor = ...
                    Colours.warning;
            end
        catch ME
            modelStateLabel.Text = ...
                'MODEL ERROR';
            modelStateLabel.FontColor = ...
                Colours.fail;
            uialert( ...
                fig, ...
                ME.message, ...
                'Vehicle Model Error');
        end
    end
%% ============================================================
% UPDATE TRADE-OFF MAP
% ============================================================
    function updateTradeoffMap( ...
        CurrentSetup, ...
        CurrentOperating)
        currentSpeedKmh = ...
            CurrentOperating.speed * 3.6;
        %% ----------------------------------------------------
        % CALCULATE / REFRESH TRADE-OFF STUDY
        %
        % The full spring grid is recalculated ONLY when
        % vehicle speed changes.
        %
        % Changing spring values simply moves the current
        % setup marker across the existing cached map.
        % -----------------------------------------------------
        if isempty(CachedTradeoffStudy) || ...
                abs(currentSpeedKmh - CachedTradeoffSpeed) > 1e-9
            modelStateLabel.Text = ...
                'CALCULATING TRADE-OFF MAP...';
            modelStateLabel.FontColor = ...
                Colours.warning;
            drawnow;
            CachedTradeoffStudy = ...
                springTradeoffMap( ...
                Vehicle, ...
                BaselineSetup, ...
                CurrentOperating, ...
                Tyre, ...
                Constants, ...
                AeroMap, ...
                frontSpringValues, ...
                rearSpringValues);
            CachedTradeoffSpeed = ...
                currentSpeedKmh;
        end
        Study = CachedTradeoffStudy;
        %% ----------------------------------------------------
        % EXTRACT GRID DATA
        % -----------------------------------------------------
        X = Study.FrontSpringGrid;
        Y = Study.RearSpringGrid;
        Z = Study.Results.downforce;
        Valid = ...
            logical(Study.Results.allValid);
        %% ----------------------------------------------------
        % CLEAR AXES
        % -----------------------------------------------------
        cla(analysisAxes);
        hold(analysisAxes,'on');
        %% ----------------------------------------------------
        % DETERMINE CLEAN DOWNFORCE CONTOUR LEVELS
        %
        % Use sensible 100 N engineering intervals instead of
        % MATLAB-generated values such as 7690.4586 N.
        % -----------------------------------------------------
        finiteDownforce = ...
            Z(isfinite(Z));
        minDownforce = ...
            min(finiteDownforce);
        maxDownforce = ...
            max(finiteDownforce);
        contourMin = ...
            floor(minDownforce / 100) * 100;
        contourMax = ...
            ceil(maxDownforce / 100) * 100;
        contourLevels = ...
            contourMin : 100 : contourMax;
        % Safety fallback if the range becomes very small
        if numel(contourLevels) < 3
            contourLevels = ...
                linspace( ...
                minDownforce, ...
                maxDownforce, ...
                5);
        end
        %% ----------------------------------------------------
        % FILLED DOWNFORCE MAP
        % -----------------------------------------------------
        contourf( ...
            analysisAxes, ...
            X, ...
            Y, ...
            Z, ...
            contourLevels, ...
            'LineStyle', ...
            'none');
        %% ----------------------------------------------------
        % COLOUR BAR
        % -----------------------------------------------------
        cb = ...
            colorbar(analysisAxes);
        cb.Label.String = ...
            'Downforce [N]';
        %% ----------------------------------------------------
        % DOWNFORCE CONTOUR LINES
        % -----------------------------------------------------
        [C,hContours] = ...
            contour( ...
            analysisAxes, ...
            X, ...
            Y, ...
            Z, ...
            contourLevels, ...
            'LineColor', ...
            [0.20 0.20 0.20], ...
            'LineWidth', ...
            0.8);
        %% ----------------------------------------------------
        % CLEAN CONTOUR LABELS
        %
        % Contour levels are already rounded to 100 N, so the
        % displayed labels become:
        %
        % 7200
        % 7300
        % 7400
        % ...
        %
        % rather than long decimal values.
        % -----------------------------------------------------
        clabel( ...
            C, ...
            hContours, ...
            'FontSize', ...
            8, ...
            'Color', ...
            [0.15 0.15 0.15], ...
            'LabelSpacing', ...
            650);
        %% ----------------------------------------------------
        % AERO-PLATFORM VALIDITY BOUNDARY
        %
        % allValid:
        %
        %       0 = invalid
        %       1 = valid
        %
        % The 0.5 contour therefore identifies the boundary
        % between the two regions.
        % -----------------------------------------------------
        contour( ...
            analysisAxes, ...
            X, ...
            Y, ...
            double(Valid), ...
            [0.5 0.5], ...
            'LineColor', ...
            [0 0 0], ...
            'LineWidth', ...
            3.0);
        %% ----------------------------------------------------
        % BASELINE SETUP
        % -----------------------------------------------------
        plot( ...
            analysisAxes, ...
            BaselineSetup.springFront, ...
            BaselineSetup.springRear, ...
            'x', ...
            'MarkerSize', ...
            13, ...
            'LineWidth', ...
            2.5, ...
            'Color', ...
            Colours.accent);
        text( ...
            analysisAxes, ...
            BaselineSetup.springFront + 3, ...
            BaselineSetup.springRear, ...
            'Baseline', ...
            'FontSize', ...
            9, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            Colours.text);
        %% ----------------------------------------------------
        % CURRENT SETUP
        % -----------------------------------------------------
        plot( ...
            analysisAxes, ...
            CurrentSetup.springFront, ...
            CurrentSetup.springRear, ...
            'o', ...
            'MarkerSize', ...
            10, ...
            'LineWidth', ...
            2.5, ...
            'Color', ...
            Colours.warning);
        text( ...
            analysisAxes, ...
            CurrentSetup.springFront + 3, ...
            CurrentSetup.springRear, ...
            'Current', ...
            'FontSize', ...
            9, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            Colours.text);
        %% ----------------------------------------------------
        % MAXIMUM VALID DOWNFORCE POINT
        %
        % This is explicitly the maximum VALID downforce found
        % within the TESTED grid.
        %
        % It is NOT being described as an optimised setup.
        % -----------------------------------------------------
        if isfield(Study,'maxDownforceFrontSpring') && ...
                isfield(Study,'maxDownforceRearSpring') && ...
                isfinite(Study.maxDownforceFrontSpring) && ...
                isfinite(Study.maxDownforceRearSpring)
            plot( ...
                analysisAxes, ...
                Study.maxDownforceFrontSpring, ...
                Study.maxDownforceRearSpring, ...
                'd', ...
                'MarkerSize', ...
                9, ...
                'LineWidth', ...
                1.8, ...
                'Color', ...
                Colours.pass);
            % Position label below marker so it does not
            % disappear against the upper plot boundary.
            text( ...
                analysisAxes, ...
                Study.maxDownforceFrontSpring + 3, ...
                Study.maxDownforceRearSpring - 5, ...
                'Max Valid DF', ...
                'FontSize', ...
                8, ...
                'FontWeight', ...
                'bold', ...
                'Color', ...
                Colours.pass);
        end
        %% ----------------------------------------------------
        % AXES FORMATTING
        % -----------------------------------------------------
        grid(analysisAxes,'on');
        box(analysisAxes,'on');
        analysisAxes.GridAlpha = ...
            0.18;
        analysisAxes.Layer = ...
            'top';
        xlim( ...
            analysisAxes, ...
            [min(frontSpringValues) ...
             max(frontSpringValues)]);
        ylim( ...
            analysisAxes, ...
            [min(rearSpringValues) ...
             max(rearSpringValues)]);
        xlabel( ...
            analysisAxes, ...
            'Front Spring Rate [N/mm]');
        ylabel( ...
            analysisAxes, ...
            'Rear Spring Rate [N/mm]');
        title( ...
            analysisAxes, ...
            sprintf( ...
            'Downforce & Aero-Platform Validity — %.0f km/h', ...
            currentSpeedKmh));
    end
%% ============================================================
% INITIAL PLOT
% ============================================================
    function plotInitialState()
        cla(analysisAxes);
        hold(analysisAxes,'on');
        plot( ...
            analysisAxes, ...
            BaselineSetup.springFront, ...
            BaselineSetup.springRear, ...
            'x', ...
            'MarkerSize', ...
            12, ...
            'LineWidth', ...
            2, ...
            'Color', ...
            Colours.accent);
        text( ...
            analysisAxes, ...
            BaselineSetup.springFront + 3, ...
            BaselineSetup.springRear, ...
            'Baseline');
        grid(analysisAxes,'on');
        xlim( ...
            analysisAxes, ...
            [min(frontSpringValues) ...
             max(frontSpringValues)]);
        ylim( ...
            analysisAxes, ...
            [min(rearSpringValues) ...
             max(rearSpringValues)]);
        xlabel( ...
            analysisAxes, ...
            'Front Spring Rate [N/mm]');
        ylabel( ...
            analysisAxes, ...
            'Rear Spring Rate [N/mm]');
        title( ...
            analysisAxes, ...
            'Run Analysis to Generate Trade-Off Map');
    end
%% ============================================================
% RESET BASELINE
% ============================================================
    function resetBaseline()
        %% ----------------------------------------------------
        % INPUTS
        % -----------------------------------------------------
        frontSpringField.Value = ...
            BaselineSetup.springFront;
        rearSpringField.Value = ...
            BaselineSetup.springRear;
        frontARBField.Value = ...
            BaselineSetup.arbFront;
        rearARBField.Value = ...
            BaselineSetup.arbRear;
        frontRHField.Value = ...
            BaselineSetup.rideHeightFront;
        rearRHField.Value = ...
            BaselineSetup.rideHeightRear;
        speedField.Value = ...
            Operating.speed * 3.6;
        steerAngleField.Value = ...
            Operating.steerAngle;
        %% ----------------------------------------------------
        % PERFORMANCE
        % -----------------------------------------------------
        resetKPI( ...
            downforceValue, ...
            downforceDelta, ...
            '--- N');
        resetKPI( ...
            efficiencyValue, ...
            efficiencyDelta, ...
            '---');
        resetKPI( ...
            aeroBalanceValue, ...
            aeroBalanceDelta, ...
            '--- %');
        resetKPI( ...
            lateralAccelValue, ...
            lateralAccelDelta, ...
            '--- g');
        resetKPI( ...
            understeerValue, ...
            understeerDelta, ...
            '---');
        balanceValue.Text = ...
            '---';
        balanceValue.FontColor = ...
            Colours.muted;
        %% ----------------------------------------------------
        % PLATFORM
        % -----------------------------------------------------
        resetKPI( ...
            frontRHValue, ...
            frontRHDelta, ...
            '--- mm');
        resetKPI( ...
            rearRHValue, ...
            rearRHDelta, ...
            '--- mm');
        resetKPI( ...
            frontCompressionValue, ...
            frontCompressionDelta, ...
            '--- mm');
        resetKPI( ...
            rearCompressionValue, ...
            rearCompressionDelta, ...
            '--- mm');
        resetKPI( ...
            rakeValue, ...
            rakeDelta, ...
            '--- deg');
        frontMarginValue.Text = ...
            '--- mm';
        frontMarginValue.FontColor = ...
            Colours.text;
        rearMarginValue.Text = ...
            '--- mm';
        rearMarginValue.FontColor = ...
            Colours.text;
        %% ----------------------------------------------------
        % MODEL STATUS
        % -----------------------------------------------------
        resetStatus(aeroStatusValue);
        resetStatus(platformStatusValue);
        resetStatus(lateralStatusValue);
        resetStatus(verticalStatusValue);
        resetStatus(overallStatusValue);
        %% ----------------------------------------------------
        % ENGINEERING INTERPRETATION
        % -----------------------------------------------------
        platformInterpretation.Text = 'Run analysis to compare the current setup with baseline.';
        aeroInterpretation.Text = '---';
        balanceInterpretation.Text = '---';
        assessmentInterpretation.Text = '---';
        assessmentInterpretation.FontColor = Colours.text;
        %% ----------------------------------------------------
        % PLOT
        % -----------------------------------------------------
        plotInitialState();
        %% ----------------------------------------------------
        % FOOTER
        % -----------------------------------------------------
        modelStateLabel.Text = ...
            'BASELINE LOADED';
        modelStateLabel.FontColor = ...
            Colours.muted;
    end
%% ============================================================
% ENGINEERING INTERPRETATION LOGIC
% ============================================================
    function updateEngineeringInterpretation( ...
        KPI, BaseKPI, Status, BaseStatus, CurrentOperating, ...
        frontMinimumRH, rearMinimumRH)
        % Engineering significance thresholds. These prevent numerical
        % noise from being described as a meaningful setup effect.
        downforceThresholdN    = 10;      % [N]
        efficiencyThresholdPct = 0.10;    % [%]
        balanceThreshold       = 0.001;   % [deg/g]
        marginThresholdMm      = 0.10;    % [mm]
        currentFrontMargin = KPI.frontRideHeight - frontMinimumRH;
        currentRearMargin  = KPI.rearRideHeight  - rearMinimumRH;
        baseFrontMargin    = BaseKPI.frontRideHeight - frontMinimumRH;
        baseRearMargin     = BaseKPI.rearRideHeight  - rearMinimumRH;
        currentMinMargin = min(currentFrontMargin,currentRearMargin);
        baseMinMargin    = min(baseFrontMargin,baseRearMargin);
        marginChange     = currentMinMargin - baseMinMargin;
        % PLATFORM
        if ~BaseStatus.aeroMapValid && Status.aeroMapValid
            if baseRearMargin < 0 && currentRearMargin >= 0
                platformText = sprintf( ...
                    'Rear platform brought inside aero-map range. Minimum current margin: %+.3f mm.', ...
                    currentMinMargin);
            elseif baseFrontMargin < 0 && currentFrontMargin >= 0
                platformText = sprintf( ...
                    'Front platform brought inside aero-map range. Minimum current margin: %+.3f mm.', ...
                    currentMinMargin);
            else
                platformText = sprintf( ...
                    'Platform brought inside aero-map range. Minimum current margin: %+.3f mm.', ...
                    currentMinMargin);
            end
        elseif BaseStatus.aeroMapValid && ~Status.aeroMapValid
            platformText = sprintf( ...
                'Current setup moves outside the aero-map range. Minimum margin: %+.3f mm.', ...
                currentMinMargin);
        elseif Status.aeroMapValid
            if marginChange > marginThresholdMm
                platformText = sprintf( ...
                    'Aero-platform margin improved by %+.3f mm; minimum current margin is %+.3f mm.', ...
                    marginChange,currentMinMargin);
            elseif marginChange < -marginThresholdMm
                platformText = sprintf( ...
                    'Aero-platform margin reduced by %.3f mm; minimum current margin is %+.3f mm.', ...
                    abs(marginChange),currentMinMargin);
            else
                platformText = sprintf( ...
                    'Aero-platform margin essentially unchanged; minimum current margin is %+.3f mm.', ...
                    currentMinMargin);
            end
        else
            platformText = sprintf( ...
                'Platform remains outside the aero-map range. Minimum current margin: %+.3f mm.', ...
                currentMinMargin);
        end
        % AERO
        deltaDF = KPI.downforce - BaseKPI.downforce;
        if abs(BaseKPI.downforce) > eps
            deltaDFPct = 100 * deltaDF / BaseKPI.downforce;
        else
            deltaDFPct = NaN;
        end
        if abs(BaseKPI.aeroEfficiency) > eps
            deltaEffPct = 100 * ...
                (KPI.aeroEfficiency - BaseKPI.aeroEfficiency) / ...
                BaseKPI.aeroEfficiency;
        else
            deltaEffPct = NaN;
        end
        if abs(deltaDF) >= downforceThresholdN
            if deltaDF > 0
                dfPhrase = sprintf('Downforce +%.1f N (+%.2f%%)',deltaDF,deltaDFPct);
            else
                dfPhrase = sprintf('Downforce %.1f N (%.2f%%)',deltaDF,deltaDFPct);
            end
        else
            dfPhrase = 'Downforce essentially unchanged';
        end
        if isfinite(deltaEffPct) && abs(deltaEffPct) >= efficiencyThresholdPct
            if deltaEffPct > 0
                effPhrase = sprintf('aero efficiency +%.2f%%',deltaEffPct);
            else
                effPhrase = sprintf('aero efficiency %.2f%%',deltaEffPct);
            end
        else
            effPhrase = 'aero efficiency essentially unchanged';
        end
        aeroText = sprintf('%s; %s.',dfPhrase,effPhrase);
        % BALANCE
        deltaKus = KPI.understeerGradient - BaseKPI.understeerGradient;
        if abs(deltaKus) < balanceThreshold
            balanceText = sprintf( ...
                'Lateral balance essentially unchanged. ΔKus = %+.4f deg/g.', ...
                deltaKus);
        elseif deltaKus > 0
            balanceText = sprintf( ...
                'Balance shifts toward understeer. ΔKus = %+.4f deg/g.', ...
                deltaKus);
        else
            balanceText = sprintf( ...
                'Balance shifts toward oversteer. ΔKus = %+.4f deg/g.', ...
                deltaKus);
        end
        % ASSESSMENT
        speedKmh = CurrentOperating.speed * 3.6;
        if Status.allValid
            assessmentText = sprintf( ...
                'Current setup satisfies all model validity checks at %.0f km/h.', ...
                speedKmh);
            assessmentInterpretation.FontColor = Colours.pass;
        else
            issues = {};
            if ~Status.aeroMapValid
                currentFrontMargin = KPI.frontRideHeight - frontMinimumRH;
                currentRearMargin  = KPI.rearRideHeight - rearMinimumRH;
                if currentFrontMargin < 0 && currentRearMargin < 0
                    issues{end+1} = 'front and rear aero-platform limits'; %#ok<AGROW>
                elseif currentFrontMargin < 0
                    issues{end+1} = 'front aero-platform limit'; %#ok<AGROW>
                elseif currentRearMargin < 0
                    issues{end+1} = 'rear aero-platform limit'; %#ok<AGROW>
                else
                    issues{end+1} = 'aero-platform range'; %#ok<AGROW>
                end
            end
            if ~Status.platformConverged
                issues{end+1} = 'platform convergence'; %#ok<AGROW>
            end
            if ~Status.lateralSolverConverged
                issues{end+1} = 'lateral convergence'; %#ok<AGROW>
            end
            if ~Status.verticalLoadValid
                issues{end+1} = 'vertical-load check'; %#ok<AGROW>
            end
            if isempty(issues)
                issueText = 'model status';
            else
                issueText = strjoin(issues,', ');
            end
            assessmentText = sprintf( ...
                'Current setup requires review at %.0f km/h: %s.', ...
                speedKmh,issueText);
            assessmentInterpretation.FontColor = Colours.warning;
        end
        platformInterpretation.Text = platformText;
        aeroInterpretation.Text = aeroText;
        balanceInterpretation.Text = balanceText;
        assessmentInterpretation.Text = assessmentText;
    end
%% ============================================================
% STATUS HELPER
% ============================================================
    function setStatus( ...
        labelHandle, ...
        status)
        if status
            labelHandle.Text = ...
                'PASS';
            labelHandle.FontColor = ...
                Colours.pass;
        else
            labelHandle.Text = ...
                'CHECK';
            labelHandle.FontColor = ...
                Colours.warning;
        end
    end
%% ============================================================
% AERO-MARGIN COLOUR HELPER
% ============================================================
    function setMarginColour( ...
        labelHandle, ...
        margin)
        if margin >= 0
            labelHandle.FontColor = ...
                Colours.pass;
        else
            labelHandle.FontColor = ...
                Colours.warning;
        end
    end
%% ============================================================
% RESET KPI HELPER
% ============================================================
    function resetKPI( ...
        valueHandle, ...
        deltaHandle, ...
        defaultText)
        valueHandle.Text = ...
            defaultText;
        deltaHandle.Text = ...
            '---';
        deltaHandle.FontColor = ...
            Colours.muted;
    end
%% ============================================================
% RESET STATUS HELPER
% ============================================================
    function resetStatus(labelHandle)
        labelHandle.Text = ...
            '---';
        labelHandle.FontColor = ...
            Colours.text;
    end
end
%% ============================================================
% LOCAL FUNCTION - INPUT LABEL
% ============================================================
function label = createInputLabel( ...
    parentGrid, ...
    textString, ...
    row)
label = ...
    uilabel(parentGrid);
label.Layout.Row = ...
    row;
label.Layout.Column = ...
    1;
label.Text = ...
    textString;
label.FontSize = ...
    12;
end
%% ============================================================
% LOCAL FUNCTION - KPI ROW
% ============================================================
function [valueLabel,deltaLabel] = createKPIRow( ...
    parentGrid, ...
    row, ...
    labelText, ...
    valueText, ...
    deltaText)
nameLabel = ...
    uilabel(parentGrid);
nameLabel.Layout.Row = ...
    row;
nameLabel.Layout.Column = ...
    1;
nameLabel.Text = ...
    labelText;
nameLabel.FontSize = ...
    11;
valueLabel = ...
    uilabel(parentGrid);
valueLabel.Layout.Row = ...
    row;
valueLabel.Layout.Column = ...
    2;
valueLabel.Text = ...
    valueText;
valueLabel.HorizontalAlignment = ...
    'right';
valueLabel.FontWeight = ...
    'bold';
valueLabel.FontSize = ...
    11;
deltaLabel = ...
    uilabel(parentGrid);
deltaLabel.Layout.Row = ...
    row;
deltaLabel.Layout.Column = ...
    3;
deltaLabel.Text = ...
    deltaText;
deltaLabel.HorizontalAlignment = ...
    'right';
deltaLabel.FontSize = ...
    10;
deltaLabel.FontColor = ...
    [0.42 0.45 0.50];
end
%% ============================================================
% LOCAL FUNCTION - INTERPRETATION ROW
% ============================================================
function valueLabel = createInterpretationRow( ...
    parentGrid, row, labelText, accentColour)
nameLabel = uilabel(parentGrid);
nameLabel.Layout.Row = row;
nameLabel.Layout.Column = 1;
nameLabel.Text = labelText;
nameLabel.FontSize = 10;
nameLabel.FontWeight = 'bold';
nameLabel.FontColor = accentColour;
valueLabel = uilabel(parentGrid);
valueLabel.Layout.Row = row;
valueLabel.Layout.Column = 2;
valueLabel.Text = '---';
valueLabel.FontSize = 10;
valueLabel.FontColor = [0.18 0.20 0.23];
valueLabel.WordWrap = 'on';
end
%% ============================================================
% LOCAL FUNCTION - STATUS ROW
% ============================================================
function statusLabel = createStatusRow( ...
    parentGrid, ...
    row, ...
    labelText)
nameLabel = ...
    uilabel(parentGrid);
nameLabel.Layout.Row = ...
    row;
nameLabel.Layout.Column = ...
    1;
nameLabel.Text = ...
    labelText;
nameLabel.FontSize = ...
    11;
statusLabel = ...
    uilabel(parentGrid);
statusLabel.Layout.Row = ...
    row;
statusLabel.Layout.Column = ...
    2;
statusLabel.Text = ...
    '---';
statusLabel.HorizontalAlignment = ...
    'center';
statusLabel.FontWeight = ...
    'bold';
statusLabel.FontSize = ...
    11;
end
