function Comparison = compareVehicleSetups( ...
    Vehicle, BaselineSetup, ProposedSetup, ...
    Operating, Tyre, Constants, AeroMap)
%COMPAREVEHICLESETUPS
%
% Stage 6.2 - Baseline vs Proposed Setup Comparison
%
% Runs two vehicle setups through the same validated Stage 6.1
% performance calculation engine and compares the resulting
% engineering KPIs.
%
% IMPORTANT
% ---------
% This function does not assign an arbitrary performance score.
% It reports physical changes and exposes engineering trade-offs.
%
% Numerical increases are not automatically interpreted as
% improvements. For example:
%
%   - Increased downforce may be beneficial.
%   - Increased body-mode frequency is simply a change.
%   - Increased dynamic tyre-load variation may be undesirable.
%
% This distinction becomes important in the final Stage 6 GUI.


%% ============================================================
%  1. EVALUATE BASELINE SETUP
%  ============================================================

BaselinePerformance = ...
    evaluateVehiclePerformance( ...
    Vehicle, ...
    BaselineSetup, ...
    Operating, ...
    Tyre, ...
    Constants, ...
    AeroMap);


%% ============================================================
%  2. EVALUATE PROPOSED SETUP
%  ============================================================

ProposedPerformance = ...
    evaluateVehiclePerformance( ...
    Vehicle, ...
    ProposedSetup, ...
    Operating, ...
    Tyre, ...
    Constants, ...
    AeroMap);


%% ============================================================
%  3. EXTRACT KPI STRUCTURES
%  ============================================================

B = BaselinePerformance.KPI;
P = ProposedPerformance.KPI;


%% ============================================================
%  4. SETUP CHANGES
%  ============================================================

SetupChange.springFront = ...
    calculateChange( ...
    BaselineSetup.springFront, ...
    ProposedSetup.springFront);

SetupChange.springRear = ...
    calculateChange( ...
    BaselineSetup.springRear, ...
    ProposedSetup.springRear);

SetupChange.arbFront = ...
    calculateChange( ...
    BaselineSetup.arbFront, ...
    ProposedSetup.arbFront);

SetupChange.arbRear = ...
    calculateChange( ...
    BaselineSetup.arbRear, ...
    ProposedSetup.arbRear);

SetupChange.rideHeightFront = ...
    calculateChange( ...
    BaselineSetup.rideHeightFront, ...
    ProposedSetup.rideHeightFront);

SetupChange.rideHeightRear = ...
    calculateChange( ...
    BaselineSetup.rideHeightRear, ...
    ProposedSetup.rideHeightRear);

SetupChange.camberFront = ...
    calculateChange( ...
    BaselineSetup.camberFront, ...
    ProposedSetup.camberFront);

SetupChange.camberRear = ...
    calculateChange( ...
    BaselineSetup.camberRear, ...
    ProposedSetup.camberRear);

SetupChange.toeFront = ...
    calculateChange( ...
    BaselineSetup.toeFront, ...
    ProposedSetup.toeFront);

SetupChange.toeRear = ...
    calculateChange( ...
    BaselineSetup.toeRear, ...
    ProposedSetup.toeRear);


%% ============================================================
%  5. LATERAL PERFORMANCE CHANGES
%  ============================================================

Change.lateralAccelerationG = ...
    calculateChange( ...
    B.lateralAccelerationG, ...
    P.lateralAccelerationG);

Change.yawRateDeg = ...
    calculateChange( ...
    B.yawRateDeg, ...
    P.yawRateDeg);

Change.cgSideslipDeg = ...
    calculateChange( ...
    B.cgSideslipDeg, ...
    P.cgSideslipDeg);

Change.understeerGradient = ...
    calculateChange( ...
    B.understeerGradient, ...
    P.understeerGradient);

Change.frontCorneringStiffness = ...
    calculateChange( ...
    B.frontCorneringStiffness, ...
    P.frontCorneringStiffness);

Change.rearCorneringStiffness = ...
    calculateChange( ...
    B.rearCorneringStiffness, ...
    P.rearCorneringStiffness);


%% ============================================================
%  6. AERODYNAMIC PERFORMANCE CHANGES
%  ============================================================

Change.CL = ...
    calculateChange(B.CL, P.CL);

Change.CD = ...
    calculateChange(B.CD, P.CD);

Change.aeroEfficiency = ...
    calculateChange( ...
    B.aeroEfficiency, ...
    P.aeroEfficiency);

Change.downforce = ...
    calculateChange( ...
    B.downforce, ...
    P.downforce);

Change.downforceToWeight = ...
    calculateChange( ...
    B.downforceToWeight, ...
    P.downforceToWeight);

Change.aeroBalanceFrontPercent = ...
    calculateChange( ...
    B.aeroBalanceFrontPercent, ...
    P.aeroBalanceFrontPercent);


%% ============================================================
%  7. PLATFORM CHANGES
%  ============================================================

Change.frontRideHeight = ...
    calculateChange( ...
    B.frontRideHeight, ...
    P.frontRideHeight);

Change.rearRideHeight = ...
    calculateChange( ...
    B.rearRideHeight, ...
    P.rearRideHeight);

Change.frontCompression = ...
    calculateChange( ...
    B.frontCompression, ...
    P.frontCompression);

Change.rearCompression = ...
    calculateChange( ...
    B.rearCompression, ...
    P.rearCompression);

Change.heave = ...
    calculateChange( ...
    B.heave, ...
    P.heave);

Change.rakeAngleDeg = ...
    calculateChange( ...
    B.rakeAngleDeg, ...
    P.rakeAngleDeg);


%% ============================================================
%  8. SUSPENSION CHANGES
%  ============================================================

Change.frontWheelRate = ...
    calculateChange( ...
    B.frontWheelRate, ...
    P.frontWheelRate);

Change.rearWheelRate = ...
    calculateChange( ...
    B.rearWheelRate, ...
    P.rearWheelRate);

Change.totalHeaveStiffness = ...
    calculateChange( ...
    B.totalHeaveStiffness, ...
    P.totalHeaveStiffness);


%% ============================================================
%  9. AERO-MAP MARGINS
%  ============================================================
%
% Positive margin = inside the permitted aero-map boundary.
% Negative margin = outside the map.
%

Margin.Baseline.frontLower = ...
    B.frontRideHeight - AeroMap.minFrontRH;

Margin.Baseline.frontUpper = ...
    AeroMap.maxFrontRH - B.frontRideHeight;

Margin.Baseline.rearLower = ...
    B.rearRideHeight - AeroMap.minRearRH;

Margin.Baseline.rearUpper = ...
    AeroMap.maxRearRH - B.rearRideHeight;


Margin.Proposed.frontLower = ...
    P.frontRideHeight - AeroMap.minFrontRH;

Margin.Proposed.frontUpper = ...
    AeroMap.maxFrontRH - P.frontRideHeight;

Margin.Proposed.rearLower = ...
    P.rearRideHeight - AeroMap.minRearRH;

Margin.Proposed.rearUpper = ...
    AeroMap.maxRearRH - P.rearRideHeight;


%% Minimum margin to any map boundary

Margin.Baseline.minimum = ...
    min([ ...
    Margin.Baseline.frontLower, ...
    Margin.Baseline.frontUpper, ...
    Margin.Baseline.rearLower, ...
    Margin.Baseline.rearUpper]);

Margin.Proposed.minimum = ...
    min([ ...
    Margin.Proposed.frontLower, ...
    Margin.Proposed.frontUpper, ...
    Margin.Proposed.rearLower, ...
    Margin.Proposed.rearUpper]);


%% ============================================================
%  10. ENGINEERING INDICATORS
%  ============================================================
%
% These indicators describe the direction of change.
%
% They deliberately do NOT create an overall score.
%

Indicators.downforceChange = ...
    directionText(Change.downforce.absolute);

Indicators.aeroEfficiencyChange = ...
    directionText(Change.aeroEfficiency.absolute);

Indicators.frontRideHeightChange = ...
    directionText(Change.frontRideHeight.absolute);

Indicators.rearRideHeightChange = ...
    directionText(Change.rearRideHeight.absolute);

Indicators.heaveChange = ...
    directionText(Change.heave.absolute);

Indicators.understeerGradientChange = ...
    directionText(Change.understeerGradient.absolute);

Indicators.frontCorneringStiffnessChange = ...
    directionText(Change.frontCorneringStiffness.absolute);

Indicators.rearCorneringStiffnessChange = ...
    directionText(Change.rearCorneringStiffness.absolute);


%% ============================================================
%  11. VALIDITY CHANGE
%  ============================================================

Validity.baselineValid = ...
    BaselinePerformance.Status.allValid;

Validity.proposedValid = ...
    ProposedPerformance.Status.allValid;

Validity.baselineAeroMapValid = ...
    BaselinePerformance.Status.aeroMapValid;

Validity.proposedAeroMapValid = ...
    ProposedPerformance.Status.aeroMapValid;


if ~Validity.baselineValid && Validity.proposedValid

    Validity.description = ...
        'Proposed setup restores full model validity';

elseif Validity.baselineValid && ~Validity.proposedValid

    Validity.description = ...
        'Proposed setup leaves the validated model domain';

elseif Validity.baselineValid && Validity.proposedValid

    Validity.description = ...
        'Both setups remain within the validated model domain';

else

    Validity.description = ...
        'Both setups contain model-domain validity warnings';

end


%% ============================================================
%  12. STORE COMPARISON
%  ============================================================

Comparison.BaselineSetup = ...
    BaselineSetup;

Comparison.ProposedSetup = ...
    ProposedSetup;

Comparison.BaselinePerformance = ...
    BaselinePerformance;

Comparison.ProposedPerformance = ...
    ProposedPerformance;

Comparison.SetupChange = ...
    SetupChange;

Comparison.Change = ...
    Change;

Comparison.Margin = ...
    Margin;

Comparison.Indicators = ...
    Indicators;

Comparison.Validity = ...
    Validity;


end


%% ============================================================
%  LOCAL FUNCTION - CALCULATE CHANGE
%  ============================================================

function Change = calculateChange(baselineValue, proposedValue)

Change.baseline = baselineValue;
Change.proposed = proposedValue;

Change.absolute = ...
    proposedValue - baselineValue;


if abs(baselineValue) > 1e-12

    Change.percent = ...
        100 * Change.absolute / abs(baselineValue);

else

    Change.percent = NaN;

end

end


%% ============================================================
%  LOCAL FUNCTION - DIRECTION TEXT
%  ============================================================

function text = directionText(change)

tolerance = 1e-10;

if change > tolerance

    text = 'INCREASED';

elseif change < -tolerance

    text = 'DECREASED';

else

    text = 'UNCHANGED';

end

end